### ISSUE TITLE
Batch dimension disappears/re-appears

### ISSUE THREAD

**Issue by oliver-batchelor** [NVIDIA-AI-IOT/torch2trt#116]
When creating a tensorrt model, it seems it usually omits the batch dimension - but sometimes it pops up again. Is this because of use of an unsupported operation (I notice that there is no upscaled._trt member)?

Minimal example below.

```
[TensorRT] ERROR: (Unnamed Layer* 2) [Concatenation]: all concat input tensors must have the same number of dimensions, but mismatch at input 1. Input 0 shape: [1,3,50,50], Input 1 shape: [3,50,50]
[TensorRT] ERROR: Could not compute dimensions for output_0, because the network is not valid
```

```
from torch import nn
import torch.nn.functional as F

import torch
from torch2trt import torch2trt


class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.pool = nn.AvgPool2d(2, ceil_mode=True)

    def forward(self, input):

        upscaled = F.pixel_shuffle(input, 2)
        x = self.pool(upscaled)

        return torch.cat([x, input], dim=1)

model = MyModel()

dummy = torch.ones((1, 64, 50, 50)).cuda()
model(dummy)
model = torch2trt(model, [dummy])


```

 I compiled torch2trt with the plugin enabled and tried interpolate instead - and I get this error:

  ```
File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch2trt/torch2trt.py", line 198, in wrapper
    converter(ctx)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch2trt/converters/interpolate/interpolate.py", line 35, in convert_interpolate
    plugin = get_interpolate_plugin(size=size, mode=mode, align_corners=align_corners)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch2trt/converters/interpolate/interpolate.py", line 11, in get_interpolate_plugin
    creator = [c for c in registry.plugin_creator_list if c.name == PLUGIN_NAME and c.plugin_namespace == 'torch2trt'][0]
IndexError: list index out of range

```

**Comment by jaybdub** [comment]
Hi Saul are,

Thanks for reaching out!  I believe the pixel shuffle layer is not implemented.  I will have to see if this can be supported.

Sorry for the opaque errors.

Please let me know if you have any questions.

Best,
John

**Comment by saulzar** [comment]
Ah, thanks John. 

I could make do with using interpolate, but can't for the life of me seem to get the torch2trt to install correctly with the plugin enabled inside a conda sandbox (see error below). There were a number of posts about it which made it look like it was something to do with linking an incorrect libprotobuf - but the suggested fixes didn't seem to make a difference here.


```
File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch2trt/torch2trt.py", line 198, in wrapper
  converter(ctx)
File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch2trt/converters/interpolate/interpolate.py", line 35, in convert_interpolate
  plugin = get_interpolate_plugin(size=size, mode=mode, align_corners=align_corners)
File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch2trt/converters/interpolate/interpolate.py", line 11, in get_interpolate_plugin
  creator = [c for c in registry.plugin_creator_list if c.name == PLUGIN_NAME and c.plugin_namespace == 'torch2trt'][0]
IndexError: list index out of range
```

**Comment by jaybdub** [comment]
Hi saulzar,

Could you try commenting out this try-catch statement and repeating?

https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/torch2trt/__init__.py#L17

This way we may be able to see the error that occurs when an attempt is made to load the plugin library.

Best,
John

**Comment by saulzar** [comment]
Ah, I see..

Traceback (most recent call last):
  File "/home/oliver/miniconda3/lib/python3.7/runpy.py", line 183, in
_run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/oliver/miniconda3/lib/python3.7/runpy.py", line 109, in
_get_module_details
    __import__(pkg_name)
  File "/home/oliver/Downloads/torch2trt/torch2trt/__init__.py", line 17,
in <module>
    load_plugins()
  File "/home/oliver/Downloads/torch2trt/torch2trt/__init__.py", line 9, in
load_plugins
    ctypes.CDLL(os.path.join(os.path.dirname(__file__), 'libtorch2trt.so'))
  File "/home/oliver/miniconda3/lib/python3.7/ctypes/__init__.py", line
356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/oliver/Downloads/torch2trt/torch2trt/libtorch2trt.so:
undefined symbol: _ZN3c1011HIPTensorIdEv

**Comment by saulzar** [comment]
Ah, I see.. this seems to be the crux of it.

OSError: /home/oliver/miniconda3/lib/python3.7/site-packages/torch2trt/libtorch2trt.so: undefined symbol: _ZN3c1011HIPTensorIdEv

```
Traceback (most recent call last):
  File "/home/oliver/miniconda3/lib/python3.7/runpy.py", line 183, in
_run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/oliver/miniconda3/lib/python3.7/runpy.py", line 109, in
_get_module_details
    __import__(pkg_name)
  File "/home/oliver/Downloads/torch2trt/torch2trt/__init__.py", line 17,
in <module>
    load_plugins()
  File "/home/oliver/Downloads/torch2trt/torch2trt/__init__.py", line 9, in
load_plugins
    ctypes.CDLL(os.path.join(os.path.dirname(pes/__init__.py", line
356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/oliver/miniconda3/lib/pyth__file__), 'libtorch2trt.so'))
  File "/home/oliver/miniconda3/lib/python3.7/ctypes/__init__.py", line
356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/oliver/miniconda3/lib/python3.7/site-packages/torch2trt/libtorch2trt.so: undefined symbol: _ZN3c1011HIPTensorIdEv
```

**Comment by saulzar** [comment]
I have another system which is similar, but a different undefined symbol - all these seem like they might be because the build system is linking system libraries where it should be linking libraries from the conda environment?!

```
raceback (most recent call last):
  File "/home/oliver/miniconda3/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/oliver/miniconda3/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/oliver/Downloads/torch2trt/torch2trt/__init__.py", line 17, in <module>
    load_plugins()
  File "/home/oliver/Downloads/torch2trt/torch2trt/__init__.py", line 9, in load_plugins
    ctypes.CDLL(os.path.join(os.path.dirname(__file__), 'libtorch2trt.so'))
  File "/home/oliver/miniconda3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/oliver/Downloads/torch2trt/torch2trt/libtorch2trt.so: undefined symbol: _ZN3c1014DeviceTypeNameB5cxx11ENS_10DeviceTypeEb

```
`

**Comment by saulzar** [comment]
Finally I managed to compile a working version of plugins, it required recompiling pytorch with g++6 (I could not get torch2trt working with g++ 4.8 and libprotobuf), and adding my conda install prefix to the build.py, I guess there should be an automated way to do discover the current environment prefix and use that?
