### ISSUE TITLE
AttributeError: module 'tensorrt' has no attribute 'Logger'

### ISSUE THREAD

**Issue by amajidsinar** [NVIDIA-AI-IOT/torch2trt#143]
This happened when I tried to import tensorrt

`>>> import tensorrt as trt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/jedi/yolov3/tensorrt.py", line 8, in <module>
    from torch2trt import torch2trt
  File "/jedi/yolov3/torch2trt/torch2trt/__init__.py", line 1, in <module>
    from .torch2trt import *
  File "/jedi/yolov3/torch2trt/torch2trt/torch2trt.py", line 345, in <module>
    def torch2trt(module, inputs, input_names=None, output_names=None, log_level=trt.Logger.ERROR, max_batch_size=1,
AttributeError: module 'tensorrt' has no attribute 'Logger'`

I'm currently using docker provided by the nvidia nvcr.io/nvidia/tensorrt for both tagging version 19.08-py3 and 19.10-py3 with no luck

thanks !!!

**Comment by Sjoerdtvanvliet** [comment]
Got it fixed? Got the same probldm
