### ISSUE TITLE
Large gap between y and y_trt, why?

### ISSUE THREAD

**Issue by zhoulukuan** [NVIDIA-AI-IOT/torch2trt#156]
I try to convert a pytorch model to trt model. I used the example code in usage part and replace alexnet with my own model. However, I got this result:
```
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
tensor(1.3865, device='cuda:0', grad_fn=<MaxBackward1>)
```
It seems that there is a big difference between outputs. I have two questions to ask:
1. How does torch2trt handle unsupported methods? Skip or use pytorch operation?
2. Does the warning have a direct impact on the results? Or other factors, such as float or Int precision affecting the results?

**Comment by zhoulukuan** [comment]
Besides, I got different results from. It's strange.
```
print(torch.max(torch.abs(y - y_trt)))
```

**Comment by zhoulukuan** [comment]
Results of test.sh and test ohter function such as max_pool2d
```
(mm) zlk@user-SYS-7048GR-TR:~/torch2trt$ ./test.sh temp.md
| torch2trt.tests.torchvision.classification.alexnet | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 1.53E-05 | 870 | 1.45e+03 | 1.29 | 0.772 |
| torch2trt.tests.torchvision.classification.squeezenet1_0 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 2.44E-04 | 224 | 1.57e+03 | 4.37 | 0.694 |
| torch2trt.tests.torchvision.classification.squeezenet1_1 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 4.88E-04 | 205 | 2.11e+03 | 4.36 | 0.562 |
| torch2trt.tests.torchvision.classification.resnet18 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 3.91E-03 | 307 | 882 | 3.24 | 1.08 |
| torch2trt.tests.torchvision.classification.resnet34 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 3.12E-02 | 172 | 628 | 5.76 | 1.5 |
| torch2trt.tests.torchvision.classification.resnet50 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 6.25E-02 | 117 | 358 | 8.38 | 2.73 |
| torch2trt.tests.torchvision.classification.resnet101 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 0.00E+00 | 61.1 | 223 | 16.2 | 4.59 |
| torch2trt.tests.torchvision.classification.resnet152 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 0.00E+00 | 39.4 | 161 | 25 | 6.36 |
| torch2trt.tests.torchvision.classification.densenet121 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 1.95E-03 | 42.3 | 333 | 21.5 | 2.86 |
| torch2trt.tests.torchvision.classification.densenet169 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 1.95E-03 | 31 | 242 | 31.7 | 4.1 |
| torch2trt.tests.torchvision.classification.densenet201 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 1.95E-03 | 23.5 | 191 | 42.2 | 5.3 |
| torch2trt.tests.torchvision.classification.densenet161 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 1.95E-03 | 34.6 | 164 | 28.3 | 6.2 |
| torch2trt.tests.torchvision.classification.vgg11 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 2.44E-04 | 330 | 510 | 3.06 | 2.04 |
| torch2trt.tests.torchvision.classification.vgg13 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 1.68E-04 | 262 | 410 | 3.83 | 2.51 |
| torch2trt.tests.torchvision.classification.vgg16 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 2.44E-04 | 223 | 331 | 4.61 | 3.1 |
| torch2trt.tests.torchvision.classification.vgg19 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 2.44E-04 | 193 | 279 | 5.36 | 3.67 |
| torch2trt.tests.torchvision.classification.vgg11_bn | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 2.44E-04 | 264 | 472 | 3.45 | 2.05 |
| torch2trt.tests.torchvision.classification.vgg13_bn | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 1.83E-04 | 245 | 409 | 4.18 | 2.52 |
| torch2trt.tests.torchvision.classification.vgg16_bn | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 2.44E-04 | 205 | 333 | 5 | 3.09 |
| torch2trt.tests.torchvision.classification.vgg19_bn | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 1.83E-04 | 176 | 276 | 5.79 | 3.69 |
| torch2trt.tests.torchvision.classification.mobilenet_v2 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 0.00E+00 | 110 | 905 | 7.21 | 1.04 |
(mm) zlk@user-SYS-7048GR-TR:~/torch2trt$ python -m torch2trt.test --name=max_pool2d
| torch2trt.converters.max_pool2d.test_MaxPool2d_without_ceil_mode | float32 | [(1, 3, 5, 7)] | {} | 0.00E+00 | 3.8e+04 | 1.05e+04 | 0.0511 | 0.113 |
| torch2trt.converters.max_pool2d.test_MaxPool2d_without_ceil_mode | float32 | [(1, 3, 4, 6)] | {} | 0.00E+00 | 3.69e+04 | 1.04e+04 | 0.0531 | 0.113 |
| torch2trt.converters.max_pool2d.test_MaxPool2d_with_ceil_mode | float32 | [(1, 3, 5, 7)] | {} | 0.00E+00 | 3.81e+04 | 1.05e+04 | 0.0548 | 0.112 |
| torch2trt.converters.max_pool2d.test_MaxPool2d_with_ceil_mode | float32 | [(1, 3, 4, 6)] | {} | 0.00E+00 | 3.78e+04 | 1.04e+04 | 0.053 | 0.111 |
(mm) zlk@user-SYS-7048GR-TR:~/torch2trt$ python -m torch2trt.test --name=interpolate
(mm) zlk@user-SYS-7048GR-TR:~/torch2trt$

```

**Comment by jaybdub** [comment]
Hi zhoulukuan,

Thanks for reaching out!

It seems from the error that the protocol buffer compiler that you have installed does not support proto3 syntax.

Did you install protobuf using the commands in the README?

```bash
sudo apt-get install libprotobuf* protobuf-compiler ninja-build
```

Best,
John

**Comment by zhoulukuan** [comment]
@jaybdub Thanks for your reply. I have installed protobuf using commands in the README. However, I still have problems:
```
(mm) zlk@user-SYS-7048GR-TR:~/torch2trt$ sudo apt-get install libprotobuf* protobuf-compiler ninja-build
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libprotobuf-lite9v5' for glob 'libprotobuf*'
Note, selecting 'libprotobuf-c-dev' for glob 'libprotobuf*'
Note, selecting 'libprotobuf-c0-dev' for glob 'libprotobuf*'
Note, selecting 'libprotobuf-java' for glob 'libprotobuf*'
Note, selecting 'libprotobuf-c1' for glob 'libprotobuf*'
Note, selecting 'libprotobuf-lite9' for glob 'libprotobuf*'
Note, selecting 'libprotobuf9' for glob 'libprotobuf*'
Note, selecting 'libprotobuf-c1-dbg' for glob 'libprotobuf*'
Note, selecting 'libprotobuf9v5' for glob 'libprotobuf*'
Note, selecting 'libprotobuf-dev' for glob 'libprotobuf*'
Note, selecting 'libprotobuf-c-dev' instead of 'libprotobuf-c0-dev'
libprotobuf-dev is already the newest version (2.6.1-1.3).
libprotobuf-lite9v5 is already the newest version (2.6.1-1.3).
libprotobuf9v5 is already the newest version (2.6.1-1.3).
protobuf-compiler is already the newest version (2.6.1-1.3).
libprotobuf-c-dev is already the newest version (1.2.1-1).
libprotobuf-c1 is already the newest version (1.2.1-1).
libprotobuf-c1-dbg is already the newest version (1.2.1-1).
libprotobuf-java is already the newest version (2.6.1-1.3).
ninja-build is already the newest version (1.5.1-0.1ubuntu1).
The following package was automatically installed and is no longer required:
  snapd-login-service
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 27 not upgraded.
(mm) zlk@user-SYS-7048GR-TR:~/torch2trt$ python setup.py install --plugins
running install
Building in plugin support
[2/4] protoc torch2trt/converters/interpolate/interpolate.proto --cpp_out=. --python_out=.
FAILED: protoc torch2trt/converters/interpolate/interpolate.proto --cpp_out=. --python_out=.
torch2trt/converters/interpolate/interpolate.proto:1:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
[2/4] g++ -c -fPIC torch2trt/converters/interpolate/interpolate.cpp -I/usr/loc...include/torch/csrc/api/include -I. -std=c++11 -I/usr/include/aarch64-linux-gn
FAILED: g++ -c -fPIC torch2trt/converters/interpolate/interpolate.cpp -I/usr/local/cuda/include -I/home/zlk/anaconda3/envs/mm/lib/python3.6/site-packages/torch/include -I/home/zlk/anaconda3/envs/mm/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I. -std=c++11 -I/usr/include/aarch64-linux-gnu
torch2trt/converters/interpolate/interpolate.cpp:2:21: fatal error: NvInfer.h: No such file or directory
compilation terminated.
ninja: build stopped: subcommand failed.
running build
running build_py
running install_lib
running install_egg_info
running egg_info
writing torch2trt.egg-info/PKG-INFO
writing dependency_links to torch2trt.egg-info/dependency_links.txt
writing top-level names to torch2trt.egg-info/top_level.txt
reading manifest file 'torch2trt.egg-info/SOURCES.txt'
writing manifest file 'torch2trt.egg-info/SOURCES.txt'
removing '/home/zlk/anaconda3/envs/mm/lib/python3.6/site-packages/torch2trt-0.0.2-py3.6.egg-info' (and everything under it)
Copying torch2trt.egg-info to /home/zlk/anaconda3/envs/mm/lib/python3.6/site-packages/torch2trt-0.0.2-py3.6.egg-info
running install_scripts

```

**Comment by zhoulukuan** [comment]
@jaybdub According to #20 , I compiled plugins successfully and got such results.
```
tensor(-6.3321, device='cuda:0', grad_fn=<MaxBackward1>)
tensor(-6.3321, device='cuda:0')
tensor(7.6294e-06, device='cuda:0', grad_fn=<MaxBackward1>)
```
But I still want to know, why we need to set `model.eval()` before use `torch2trt`?

**Comment by jaybdub** [comment]
Hi zhoulukuan,

The model behavior changes when calling ``model.eval()``.  For example, by calling ``model.eval`` we fix the ``BatchNorm2d`` to use the running average and mean activation values, rather than those computed on each batch.  This can have dramatic impacts when the batch size is small, like 1, which it often is.

I believe there was another issue that required calling ``model.eval()`` but I forget exactly what that was at this time.

Please let me know if this helps.

Best,
John

**Comment by liguoyu666** [comment]
> @jaybdub Hi, I update protoc 2 to 3 and change `trt_inc_dr/trt_lib_dir` in setup.py and reinstall plugins, it seems to be successful.
> 
> ```
> (mm) zlk@user-SYS-7048GR-TR:~/torch2trt$ python setup.py install --plugins
> running install
> Building in plugin support
> ninja: no work to do.
> running build
> running build_py
> running install_lib
> running install_egg_info
> running egg_info
> writing torch2trt.egg-info/PKG-INFO
> writing dependency_links to torch2trt.egg-info/dependency_links.txt
> writing top-level names to torch2trt.egg-info/top_level.txt
> reading manifest file 'torch2trt.egg-info/SOURCES.txt'
> writing manifest file 'torch2trt.egg-info/SOURCES.txt'
> removing '/home/zlk/anaconda3/envs/mm/lib/python3.6/site-packages/torch2trt-0.0.2-py3.6.egg-info' (and everything under it)
> Copying torch2trt.egg-info to /home/zlk/anaconda3/envs/mm/lib/python3.6/site-packages/torch2trt-0.0.2-py3.6.egg-info
> running install_scripts
> ```
> 
> However, when I test interploate module `python -m torch2trt.test --name=interpolate`, I got error:
> 
> ```
> Traceback (most recent call last):
>   File "/home/zlk/anaconda3/envs/mm/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/zlk/anaconda3/envs/mm/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/zlk/torch2trt/torch2trt/test.py", line 109, in <module>
>     max_error, fps, fps_trt, ms, ms_trt = run(test)
>   File "/home/zlk/torch2trt/torch2trt/test.py", line 23, in run
>     module_trt = torch2trt(module, inputs_conversion, **self.torch2trt_kwargs)
>   File "/home/zlk/torch2trt/torch2trt/torch2trt.py", line 363, in torch2trt
>     outputs = module(*inputs)
>   File "/home/zlk/anaconda3/envs/mm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/zlk/torch2trt/torch2trt/converters/interpolate/interpolate.py", line 50, in forward
>     return F.interpolate(x, self.size, mode=self.mode, align_corners=self.align_corners)
>   File "/home/zlk/torch2trt/torch2trt/torch2trt.py", line 201, in wrapper
>     converter['converter'](ctx)
>   File "/home/zlk/torch2trt/torch2trt/converters/interpolate/interpolate.py", line 35, in convert_interpolate
>     plugin = get_interpolate_plugin(size=size, mode=mode, align_corners=align_corners)
>   File "/home/zlk/torch2trt/torch2trt/converters/interpolate/interpolate.py", line 11, in get_interpolate_plugin
>     creator = [c for c in registry.plugin_creator_list if c.name == PLUGIN_NAME and c.plugin_namespace == 'torch2trt'][0]
> IndexError: list index out of range
> ```

Hello, I met the same problem, and I updated protoc 2 to 3, but  how to change `trt_inc_dr/trt_lib_dir` in setup.py ?
