### ISSUE TITLE
Can not load pre-saved model in python 2.7

### ISSUE THREAD

**Issue by jario-jin** [NVIDIA-AI-IOT/torch2trt#162]
my environment:
python 2.7.15
pytorch 1.3.1
tensorrt 6.0.1
when I exec:
```
model = TRTModule()
model.load_state_dict(torch.load(trt_model_fn))
```

I got
```
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin interpolatetorch2trt version 1
[TensorRT] ERROR: safeDeserializationUtils.cpp (259) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "det_on_tx2.py", line 41, in <module>
    model.load_state_dict(torch.load(trt_model_fn))
  File "/home/jario/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 824, in load_state_dict
    load(self)
  File "/home/jario/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 819, in load
    state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
  File "/usr/local/lib/python2.7/dist-packages/torch2trt/torch2trt.py", line 308, in _load_from_state_dict
    self.context = self.engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
```
and I checked 'libtorch2trt.so', it already here, I don't know why cannot load it. 
```
/usr/local/lib/python2.7/dist-packages/torch2trt/libtorch2trt.so
```

**Comment by jario-jin** [comment]
I added some '.so' in '__init__.py', but still not work
```
def load_plugins():
    import os
    import ctypes

    # print(os.path.join(os.path.dirname(__file__), 'libtorch2trt.so'))
    ctypes.CDLL('/home/jario/.local/lib/python2.7/site-packages/torch/lib/libc10.so')
    ctypes.CDLL('/home/jario/.local/lib/python2.7/site-packages/torch/lib/libc10_cuda.so')
    ctypes.CDLL('/home/jario/.local/lib/python2.7/site-packages/torch/lib/libtorch.so')
    ctypes.CDLL('/usr/local/cuda-10.1/lib64/libcudart.so.10.1')
    ctypes.CDLL('/usr/lib/x86_64-linux-gnu/libprotobuf.so.10')
    ctypes.CDLL('/usr/lib/x86_64-linux-gnu/libnvinfer.so.6')
    ctypes.CDLL('/home/jario/baidunetdiskdownload/torch2trt/build/lib.linux-x86_64-2.7/torch2trt/libtorch2trt.so')

    registry = trt.get_plugin_registry()
    torch2trt_creators = [c for c in registry.plugin_creator_list if c.plugin_namespace == 'torch2trt']
    for c in torch2trt_creators:
        registry.register_creator(c, 'torch2trt')
```
Now I get:
```
Traceback (most recent call last):
  File "det_on_tx2.py", line 21, in <module>
    from torch2trt import TRTModule
  File "/usr/local/lib/python2.7/dist-packages/torch2trt/__init__.py", line 28, in <module>
    load_plugins()
  File "/usr/local/lib/python2.7/dist-packages/torch2trt/__init__.py", line 17, in load_plugins
    ctypes.CDLL('/home/jario/baidunetdiskdownload/torch2trt/build/lib.linux-x86_64-2.7/torch2trt/libtorch2trt.so')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/jario/baidunetdiskdownload/torch2trt/build/lib.linux-x86_64-2.7/torch2trt/libtorch2trt.so: undefined symbol: _ZN3c1014DeviceTypeNameB5cxx11ENS_10DeviceTypeEb
```

**Comment by ouguozhen** [comment]
l meet same iusse, haved you sloved the error?

**Comment by jario-jin** [comment]
Not yet

**Comment by yosagaf** [comment]
How did you guys resolve this problem ?

**Comment by ahangchen** [comment]
any solutions for this issue? @yosagaf @jario-jin @ouguozhen

**Comment by ahangchen** [comment]
found a solution here: https://github.com/NVIDIA/TensorRT/issues/263
change the plugin name to plugin name+namespace name when inference.

**Comment by tolry418** [comment]
@ahangchen Hello. could you tell me more in detail? i can't under stand plugin name to plugin name+namespace even though there is a explanation in NVIDIA/TensorRT#263.
