### ISSUE TITLE
undefined symbol: _ZN3c1014DeviceTypeNameB5cxx11ENS_10DeviceTypeEb

### ISSUE THREAD

**Issue by aininot260** [NVIDIA-AI-IOT/torch2trt#217]
The output of my program is:
```
(tensorrt) nvidia@Dell:~/Desktop/crossnet/crossnet_trt$ python main.py
/home/nvidia/anaconda3/envs/tensorrt/lib/python3.6/site-packages/torch2trt/libtorch2trt.so: undefined symbol: _ZN3c1014DeviceTypeNameB5cxx11ENS_10DeviceTypeEb
heads {'hm': 1, 'wh': 2, 'reg': 2}
debug: ctdet
Creating model...
loaded ./models/model_hg_fod.pth, epoch 6365
step1
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
step2
ok
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    ret = detector.run(img)['results']
  File "./src/lib/detectors/base_detector.py", line 123, in run
    output, dets, forward_time = self.process(images, return_time=True)
  File "./src/lib/detectors/ctdet.py", line 52, in process
    dets = ctdet_decode(hm, wh, reg=reg, cat_spec_wh=self.opt.cat_spec_wh, K=self.opt.K)
  File "./src/lib/models/decode.py", line 465, in ctdet_decode
    batch, cat, height, width = heat.size()
ValueError: too many values to unpack (expected 4)
```
To check the undefined symbol:
```
(tensorrt) nvidia@Dell:~/github/torch2trt/build/lib/torch2trt$ c++filt _ZN3c1014DeviceTypeNameB5cxx11ENS_10DeviceTypeEb
c10::DeviceTypeName[abi:cxx11](c10::DeviceType, bool)
(tensorrt) nvidia@Dell:~/github/torch2trt/build/lib/torch2trt$ 
```
Where is this function?

My envs:
```
My OS version is ubuntu18.04 LTS.(x86_64)
My GPU is TITAN X (Pascal)/PCIe/SSE2.
My gcc and g++ version is 7.5.0.
My cuda version is 10.1.(from deb,with drivers:418.87)
My cudnn version is 7.6.5.(from deb)
my tensorrt version is 6.0.1.5.(from deb)
```

**Comment by aininot260** [comment]
I have fixed all the linking error.The undefined symbol about -lc10 and -lc10_cuda is a part of torch.The torch from conda or pip is compiled with early version of g++ without ABI flag.It's necessary to install torch and torchvision from source so the libs can work well.
But I still got the warning about 'Encountered known unsupported method torch.nn.functional.interpolate'.That's too bad.
How can I use torch2trt in x86_64 platform?What should I do?
I have made the following tests:

First,compile is ok:
```
(tensorrt) nvidia@Dell:~/github/torch2trt$ python setup.py install --plugins
running install
Building in plugin support
/home/nvidia/anaconda3/envs/tensorrt/lib/python3.6/site-packages/torch
[4/4] g++ -shared -o torch2trt/libtorc...obuf-lite -pthread -lpthread -lnvinfer
running build
running build_py
creating build
creating build/lib
creating build/lib/torch2trt
```

Second,testing is passed:
```
(tensorrt) nvidia@Dell:~/github/torch2trt$ python -m torch2trt.test --name=interpolate
success!
```
Third,I print the error log,it seems ok:
```
try:
    load_plugins()
    print('success!')
    PLUGINS_LOADED = True
except OSError as e:
    print('fail! ',e)
    PLUGINS_LOADED = False
```
Fourth,I modified the lib paths to x86_64 version:
```
def build(cuda_dir="/usr/local/cuda",
          torch_dir=imp.find_module('torch')[1],
          trt_inc_dir="/usr/include/x86_64-linux-gnu",
          trt_lib_dir="/usr/lib/x86_64-linux-gnu"):
```
When I run my program.It looks bad but no OSErrors:
```
(tensorrt) nvidia@Dell:~/Desktop/crossnet/crossnet_trt$ python main.py
success!
heads {'hm': 1, 'wh': 2, 'reg': 2}
debug: ctdet
Creating model...
loaded ./models/model_hg_fod.pth, epoch 6365
step1
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
step2
ok
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    ret = detector.run(img)['results']
  File "./src/lib/detectors/base_detector.py", line 123, in run
    output, dets, forward_time = self.process(images, return_time=True)
  File "./src/lib/detectors/ctdet.py", line 52, in process
    dets = ctdet_decode(hm, wh, reg=reg, cat_spec_wh=self.opt.cat_spec_wh, K=self.opt.K)
  File "./src/lib/models/decode.py", line 465, in ctdet_decode
    batch, cat, height, width = heat.size()
ValueError: too many values to unpack (expected 4)
```
Thanks a lot.

**Comment by RushDon** [comment]
I solved this issue eventually！！！
run  ldd -r libtorch2trt.so 
there are three symbol problems
undefined symbol: _ZN3c1014DeviceTypeNameB5cxx11ENS_10DeviceTypeEb	(torch2trt/libtorch2trt.so)
undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE	(torch2trt/libtorch2trt.so)
undefined symbol: _ZN3c107Warning4warnENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE	(torch2trt/libtorch2trt.so)

my solution is to compile and install the protobuf3.9.1 and torch2trt with g++4.8.5 instead of g++5

and add path of protobuf lib to line14 in build.py 
![image](https://user-images.githubusercontent.com/13479677/81369708-acf86980-9125-11ea-9663-eeb6dc8e3ee0.png)


good luck to everyone!
