### ISSUE TITLE
Outline how to implement the conversion for self-defined function

### ISSUE THREAD

**Issue by KelvinCPChiu** [NVIDIA-AI-IOT/torch2trt#229]
Could you outline how should we implement the conversion function for our self-defined function ?

**Comment by jaybdub** [comment]
Hi KelvinCPChiu,

Thanks for reaching out!

Do you mind sharing your use case?  Ie.  which custom function and how it's used and defined.

torch2trt is largely use case driven, so this will help guide the implementation / documentation :)

Please let me know if you have any questions.

Best,
John

**Comment by KelvinCPChiu** [comment]
Hi John,

    Thanks for the prompt reply!

Actually, I am trying to convert the Mask-RCNN Benchmark library to test the torch2trt function.
This is the library I want to convert.
https://github.com/facebookresearch/maskrcnn-benchmark

You may take a look of their demo function. I modify the demo to see whether I could directly use torch2trt over it. However, they got a self-defined class of "ImageList" which is required as an input to the model.  And I got the following error message.
_______________________________________________________________
Traceback (most recent call last):
  File "./maskrcnn-benchmark/demo/webcam.py", line 282, in <module>
    main()
  File "./maskrcnn-benchmark/demo/webcam.py", line 73, in main
    min_image_size=args.min_image_size,
  File "./maskrcnn-benchmark/demo/predictor.py", line 208, in __init__
    self.model = torch2trt(self.model_, [data], fp16_mode=True)
  File "/home/usr/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch2trt/torch2trt.py", line 377, in torch2trt
    outputs = module(*inputs)
  File "/home/user/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "./maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 48, in forward
    images = to_image_list(images)
  File "./maskrcnn-benchmark/maskrcnn_benchmark/structures/image_list.py", line 47, in to_image_list
    image_sizes = [tensor.shape[-2:] for tensor in tensors]
  File "./maskrcnn-benchmark/maskrcnn_benchmark/structures/image_list.py", line 47, in <listcomp>
    image_sizes = [tensor.shape[-2:] for tensor in tensors]
  File "/home/user/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/tensor.py", line 436, in <lambda>
    return iter(imap(lambda i: self[i], range(self.size(0))))
  File "/home/user/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch2trt/torch2trt.py", line 202, in wrapper
    converter['converter'](ctx)
  File "/home/user/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch2trt/converters/getitem.py", line 34, in convert_tensor_getitem
    num_ellipsis = input.ndim - num_slice_types(slices)
AttributeError: 'Tensor' object has no attribute 'ndim'_
_____________________________________________________________

To convert into TensorRT, I think I need to modify at least 4-5 functions to make the thing happening. Do you think that is there any simpler way to enable the conversion ?

**Comment by KelvinCPChiu** [comment]
Hi John,

Thanks for the prompt reply!

Actually, I am trying to convert the Mask-RCNN Benchmark library to test the torch2trt function.
This is the library I want to convert.

https://github.com/facebookresearch/maskrcnn-benchmark

You may take a look of their maskrcnn-benchmark/demo. I modify the demo/webcam.py and demo/predictor.py to see whether I could directly use torch2trt over it. I followed the instruction of 

> # create example data
> x = torch.ones((1, 3, 224, 224)).cuda()
> 
> # convert to TensorRT feeding sample data as input
> model_trt = torch2trt(model, [x])

Then , I modified line 141 to 144 in maskrcnn-benchmark/demo/predictor.py as follow, 

```
self.model_ = build_detection_model(cfg)
self.model_.eval()
self.device = torch.device(cfg.MODEL.DEVICE)
self.model_.to(self.device)

data = torch.randn((1, 3, 224, 224)).cuda()
self.model = torch2trt(self.model_, [data], fp16_mode=True)
```
Then I got the following error code.


[TensorRT] ERROR: (Unnamed Layer* 741) [Shuffle]: input and output volume mismatch. input volume is 3136 and output volume is 1

Traceback (most recent call last):
  File "./maskrcnn-benchmark/demo/webcam_modified.py", line 282, in <module>
    main()
  File "./maskrcnn-benchmark/demo/webcam_modified.py", line 73, in main
    min_image_size=args.min_image_size,
  File "./maskrcnn-benchmark/demo/predictor_nms.py", line 210, in __init__
    self.model = torch2trt(self.model_, [data], fp16_mode=True)
  File "/home/user/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch2trt/torch2trt.py", line 377, in torch2trt
    outputs = module(*inputs)
  File "/home/user/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "./maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 51, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/user/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "./maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 156, in forward
    anchors = self.anchor_generator(images, features)
  File "/home/user/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "./maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/anchor_generator.py", line 114, in forward
    anchors_over_all_feature_maps = self.grid_anchors(grid_sizes)
  File "./maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/anchor_generator.py", line 88, in grid_anchors
    shift_y = shift_y.reshape(-1)
  File "/home/user/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch2trt/torch2trt.py", line 202, in wrapper
    converter['converter'](ctx)
  File "/home/user/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch2trt/converters/view.py", line 10, in convert_view
    input_trt = trt_(ctx.network, input)
  File "/home/user/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch2trt/torch2trt.py", line 148, in trt_
    if len(trt_tensor.shape) < broadcast_num_dim:
ValueError: __len__() should return >= 0
```
 Do you think that is there any simpler way to enable the conversion ? 

Many Thanks,
Kelvin

**Comment by MrunaliniN** [comment]
Hello
Was this issue resolved? I have similar issue with using fasterrcnn models

**Comment by KelvinCPChiu** [comment]
This is difficult to solve as the way of conversion is done by appending a function on the original class function. If you have a self-defined function, then you need add exclusion over the conversion function. But it takes too much if there is no documentation.

Then I tried to use the TensorFlow instead. Though, there are other problems happening in tf2trt owing to the loop function in nms of tensorflow.....

**Comment by ahangchen** [comment]
@jaybdub I also need a documentation about implementing the conversion for self-defined fucntion. Currently, I want to convert [grid_sample]() in pytorch to tensortRt, I also find an [implementation](https://github.com/TrojanXu/onnxparser-trt-plugin-sample/blob/master/TensorRT/plugin/gridSamplerPlugin/gridSamplerPlugin.cpp) of grid sample as TensorRT plugin, but I don't know how to integrate this plugin into torch2trt.
