### ISSUE TITLE
module 'tensorrt' has no attribute 'Logger'

### ISSUE THREAD

**Issue by lawrencekiba** [NVIDIA-AI-IOT/torch2trt#24]
This happened when I tried using the code in the notebooks folder into a Python script

```
Traceback (most recent call last):
  File "conversion.py", line 5, in <module>
    from torch2trt import torch2trt
  File "/mnt/886E59876E596F46/PycharmProjects/torch2trt/torch2trt/__init__.py", line 1, in <module>
    from .torch2trt import *
  File "/mnt/886E59876E596F46/PycharmProjects/torch2trt/torch2trt/torch2trt.py", line 237, in <module>
    def torch2trt(module, inputs, input_names=None, output_names=None, log_level=trt.Logger.ERROR, max_batch_size=1,
AttributeError: module 'tensorrt' has no attribute 'Logger'
```

**Comment by jaybdub** [comment]
Hi  lawrencekiba,

Thanks for reaching out!  Could you share which version of PyTorch and TensorRT you are using?

Best,
John

**Comment by lawrencekiba** [comment]
Hello jaybdub, 

I was using a TensorRT 4.0. Changed to TensorRT 5 & this problem never came back.

Thank you.
