### ISSUE TITLE
[TensorRT] ERROR: (Unnamed Layer* 46) [Concatenation]: all concat input tensors must have the same dimensions except on the concatenation axis (0), but dimensions mismatched at input 1 at index 1. Input 0 shape: [1,38,46,49], Input 1 shape: [1,19,46,49]

### ISSUE THREAD

**Issue by theodorekwok** [NVIDIA-AI-IOT/torch2trt#253]
Warning: Encountered known unsupported method torch.Tensor.__hash__
Warning: Encountered known unsupported method torch.Tensor.__hash__
Warning: Encountered known unsupported method torch.Tensor.get_device
[TensorRT] ERROR: (Unnamed Layer* 46) [Concatenation]: all concat input tensors must have the same dimensions except on the concatenation axis (0), but dimensions mismatched at input 1 at index 1. Input 0 shape: [1,38,46,49], Input 1 shape: [1,19,46,49]
Traceback (most recent call last):
  File "picture_demo.py", line 74, in <module>
    model_trt = torch2trt(model, [x])
  File "/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py", line 377, in torch2trt
    outputs = module(*inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sapphire/pytorch_Realtime_Multi-Person_Pose_Estimation/lib/network/rtpose_vgg.py", line 169, in forward
    out2_1 = self.model2_1(out2)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py", line 202, in wrapper
    converter['converter'](ctx)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt/converters/Conv2d.py", line 9, in convert_Conv2d
    input_trt = trt_(ctx.network, input)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py", line 116, in trt_
    num_dim = len(t._trt.shape) # non-leaf tensors must already have _trt, get shape from that
ValueError: __len__() should return >= 0

Hi all, I tried using torch2trt to convert a pytorch model which led to this error. The model is found in this repository: https://github.com/tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation

Would greatly appreciate any help and feedback, thank you

**Comment by vineet54** [comment]
I had a similar issue. This is most likely a bug in the Concatenation converter. 
In the file `torch2trt/converters/cat.py`
Change the line https://github.com/NVIDIA-AI-IOT/torch2trt/blob/e22844a449a880123435fce7e6444f1516ebbe60/torch2trt/converters/cat.py#L17

to 

`layer.axis = dim`

**Comment by theodorekwok** [comment]
Thank you, I did the edit and currently have an attribute error: 'tuple' object has no attribute '_trt' in torch2trt.py mark_outputs, trt_tensor = torch_output._trt.

Additionally does anyone know what causes the warning message below to appear?
Warning: Encountered known unsupported method torch.Tensor.hash
Warning: Encountered known unsupported method torch.Tensor.hash
Warning: Encountered known unsupported method torch.Tensor.get_device

**Comment by vineet54** [comment]
I would recommend you use pdb to narrow down the issue.

The warning messages are thrown when there's no TensorRT converter registered for those methods. In that case, those methods run in PyTorch and not in TensorRT

**Comment by theodorekwok** [comment]
Alright thank you
