### ISSUE TITLE
torch2trt will impact the normal pytorch?

### ISSUE THREAD

**Issue by z13974509906** [NVIDIA-AI-IOT/torch2trt#262]
in pytorch, I can do the below code right:
`python
a = torch.ones((4, 3, 13, 13), dtype=torch.uint8)
b = torch.rand((4, 3, 13, 13))

c = a[b]
`

but if I use torch2trt to convert model, then execute the code. error whill occur:
`
IndexError: too many indices for tensor of dimension 4
`

Will any one reproduce this error.

Wait for your help~

**Comment by jaybdub** [comment]
Hi z13974509906,

Thanks for reaching out!  I would like to try and reproduce this issue.

Do you mind sharing the model that you were attempting to convert?

Best,
John

**Comment by z13974509906** [comment]
> Hi z13974509906,
> 
> Thanks for reaching out! I would like to try and reproduce this issue.
> 
> Do you mind sharing the model that you were attempting to convert?
> 
> Best,
> John

I have follow [pytorch yolov3](https://github.com/eriklindernoren/PyTorch-YOLOv3) . I use torch2trt convert the backbone.
After convert, pytorch became abnormal as I mention: a[b] will cause an indexerror, so I have to change it to a[b.tolist()].

**Comment by z13974509906** [comment]
> Hi z13974509906,
> 
> Thanks for reaching out! I would like to try and reproduce this issue.
> 
> Do you mind sharing the model that you were attempting to convert?
> 
> Best,
> John

you can also test `torchvison.models.resnet.resnet50()`, it can reproduce this issue

**Comment by z13974509906** [comment]
any update?

**Comment by QZ-cmd** [comment]
IndexError: too many indices for tensor of dimension 2
Hello i also found the same problem, may i have any solution

**Comment by z13974509906** [comment]
> IndexError: too many indices for tensor of dimension 2
> Hello i also found the same problem, may i have any solution

Uss tensor.tolist() may solve it. But it won't work everywhere

**Comment by QZ-cmd** [comment]
Hello where is it placed?for example x=randn（1,3,244,244）.cuda().tolist()，
Can you tell me exactly where to change? thanks

**Comment by z13974509906** [comment]
> Hello where is it placed?for example x=randn（1,3,244,244）.cuda().tolist()，
> Can you tell me exactly where to change? thanks

no, I found it only impact index. for example :  b[a]  should change to b[a.tolist()]

**Comment by QZ-cmd** [comment]
Hello, do you have an email? I have some questions for you. Thank you

**Comment by zhengjiawen** [comment]
I have the same problem, add tolist() can solve it, But I don't know why?

**Comment by QZ-cmd** [comment]
> the same problem, add tolist() can solve it, But I don't kno

Can you tell me where to add tolist (), I didn't solve the problem，thanks！

**Comment by zhengjiawen** [comment]
> > the same problem, add tolist() can solve it, But I don't kno
> 
> Can you tell me where to add tolist (), I didn't solve the problem，thanks！

add tolist() in your index tensor array

**Comment by z13974509906** [comment]
> > the same problem, add tolist() can solve it, But I don't kno
> 
> Can you tell me where to add tolist (), I didn't solve the problem，thanks！

I may be powerless. The only way to solve the problem is debugging step by step.

I recommend pdb or code

**Comment by robin5540** [comment]
I think this is the same as https://github.com/NVIDIA-AI-IOT/torch2trt/issues/270

**Comment by PressEtoRace** [comment]
I have the same problem. After debugging, I think torch2trt will really impact the original pytorch. Can anyone solve it? Or tell me the reason for the problem. Thanks!

**Comment by baheytharwat** [comment]
@dancingpipi  @PressEtoRace  Did you succeed in optimizing inference time of YOLOv3? if yes, Do you detect all objects well with a good accuracy? because the model I am working on can detect only one object!

**Comment by PressEtoRace** [comment]
> 
> 
> @dancingpipi @PressEtoRace Did you succeed in optimizing inference time of YOLOv3? if yes, Do you detect all objects well with a good accuracy? because the model I am working on can detect only one object!
I've had problems like yours. I think this is also caused by the influence of torch2trt on pytorch. My solution is to modify the NMS code in yolov3. You can print the size of the data after each operation in NMS, and you should find the problem.

**Comment by twmht** [comment]
same problem

**Comment by twmht** [comment]
I have also found out when running mask rcnn like mmdetection, it would throw cuda error at torch.tensor.any()

```
RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at ../c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7f24d0f949ab in /home/acer/nfs-share/pytorch/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xc10 (0x7f24d11d7280 in /home/acer/nfs-share/pytorch/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f24d0f7ce0d in /home/acer/nfs-share/pytorch/torch/lib/libc10.so)
frame #3: <unknown function> + 0x559d82 (0x7f24ed5eed82 in /home/acer/nfs-share/pytorch/torch/lib/libtorch_python.so)
<omitting python frames>
frame #19: __libc_start_main + 0xe7 (0x7f2538809b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #20: _start + 0x2a (0x56250f80577a in /home/acer/.pyenv/versions/pytorch_build/bin/python)

```

but after commenting out the converter of getitem (https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/torch2trt/converters/getitem.py#L32), it would work fine.

I think overriding torch.getitem is dangerous, since other torch api would use that.

**Comment by 1309123499** [comment]
> I have also found out when running mask rcnn with mmdetection, it would throw cuda error at torch.tensor.any()
> 
> ```
> RuntimeError: CUDA error: an illegal memory access was encountered
> terminate called after throwing an instance of 'c10::Error'
>   what():  CUDA error: an illegal memory access was encountered
> Exception raised from create_event_internal at ../c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
> frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7f24d0f949ab in /home/acer/nfs-share/pytorch/torch/lib/libc10.so)
> frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xc10 (0x7f24d11d7280 in /home/acer/nfs-share/pytorch/torch/lib/libc10_cuda.so)
> frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f24d0f7ce0d in /home/acer/nfs-share/pytorch/torch/lib/libc10.so)
> frame #3: <unknown function> + 0x559d82 (0x7f24ed5eed82 in /home/acer/nfs-share/pytorch/torch/lib/libtorch_python.so)
> <omitting python frames>
> frame #19: __libc_start_main + 0xe7 (0x7f2538809b97 in /lib/x86_64-linux-gnu/libc.so.6)
> frame #20: _start + 0x2a (0x56250f80577a in /home/acer/.pyenv/versions/pytorch_build/bin/python)
> ```
> 
> but after commenting out the converter of getitem (https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/torch2trt/converters/getitem.py#L32), it would work fine.
> 
> I think overriding torch.getitem is dangerous, since other torch api would use that. why not convert `torch.narrow` (https://pytorch.org/docs/stable/tensors.html)

would you please show how to solve this problem more clearly? thanks!

**Comment by SrivastavaKshitij** [comment]
Tried this example with PR #691 and there is no error.
