### ISSUE TITLE
Tensorrt Python windows 10

### ISSUE THREAD

**Issue by sundar19** [NVIDIA-AI-IOT/torch2trt#319]
How do I run this in a windows 10 OS? do you support tensorrt for windows 10 using python3?

**Comment by mathmax12** [comment]
Hi @sundar19 
I wonder have you installed the torch2trt on windows 10?

**Comment by sundar19** [comment]
No , I tried it in Jetson nano!

**Comment by abuelgasimsaadeldin** [comment]
Hi guys yes I'm wondering if torch2trt is supported on Windows OS, I've installed it and ran the setup.py successfully but when I try to import it using: 

**from torch2trt import torch2trt** 

I get the error message: 

**ModuleNotFoundError: No module named 'tensorrt'**

**Comment by mathmax12** [comment]
According to the error, you need to install tensorrt first.
What are the steps you used to install torch2trt on Windows OS?

**Comment by abuelgasimsaadeldin** [comment]
Hi @mathmax12,

For Tensorrt I followed the zip file installation steps in this link (https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-zip)

As for Torch2trt I simply cloned the repo and ran the python setup.py install on my conda environment and it was successfully installed. But I'm still receiving the error of "**No module named tensorrt**"

**Comment by mathmax12** [comment]
Have you tried to verify your installation of TensorRT
https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleMNIST?

**Comment by rgkannan676** [comment]
@abuelgasimsaadeldin  

I was able to install without plugins.

Were you able to install with the plugins? 
python setup.py install --plugins

I got the following error: 
```
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    setup(
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\torch\utils\cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\torch\utils\cpp_extension.py", line 682, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\torch\utils\cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\torch\utils\cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```
