### ISSUE TITLE
Pytorch-UNet conversor error

### ISSUE THREAD

**Issue by melezz** [NVIDIA-AI-IOT/torch2trt#32]
Hello John,

I am creating a new issue here since I tried the Unet implementation you suggested, and still getting the error that comes up when a layer is nor properly supported in tensorrt. I moved to python3.6 and tensorrt is still 5.0.6.3.

Here is the output of the error:

Traceback (most recent call last):
  File "main.py", line 57, in <module>
    machine = stateMachine(new_video_FPS, weights)
  File "/home/nvidia/Workspace/tfl/tfl-car/aux_func.py", line 534, in __init__
    self.detector = Detector(weights,True)
  File "/home/nvidia/Workspace/tfl/tfl-car/aux_func.py", line 443, in __init__
    self.model_trt = torch2trt(self.model, [data], fp16_mode=True)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.0.0-py3.6.egg/torch2trt/torch2trt.py", line 252, in torch2trt
    outputs = module(*inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nvidia/Workspace/tfl/tfl-car/unet_model.py", line 28, in forward
    x = self.up1(x5, x4)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nvidia/Workspace/tfl/tfl-car/unet_parts.py", line 70, in forward
    diffY // 2, diffY - diffY//2))
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.0.0-py3.6.egg/torch2trt/torch2trt.py", line 97, in wrapper
    converter(ctx)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.0.0-py3.6.egg/torch2trt/converters/pad.py", line 16, in convert_pad
    layer = ctx.network.add_padding(input._trt, pre_padding, post_padding)
AttributeError: 'Tensor' object has no attribute '_trt'

FYI,  not sure if this is the model you're using, but i've added layers to support https://github.com/milesial/Pytorch-UNet

Only  sigmoid and pad converters were missing.

You can convert the model by

```python
model = UNet(n_channels=3, n_classes=1).cuda().half().eval()
data = torch.zeros((1, 3, WIDTH, HEIGHT)).cuda().half()

model_trt = torch2trt(model, [data], fp16_mode=True)
```

Speedup on Xavier with my test was about 3X vs plain PyTorch!  Let me know if this works for you or you run into any issues.

Best,
John

_Originally posted by @jaybdub in https://github.com/NVIDIA-AI-IOT/torch2trt/issues/18#issuecomment-515630020_

**Comment by jaybdub** [comment]
Hi melezz,

My guess is that the converter failed on the upsampling layer.  This layer is not natively supported by TensorRT so we've implemented the ``interpolate`` plugin.  Have you successfully installed ``torch2trt`` with plugins?

```bash
sudo python3 setup.py install --plugins
```

Best,
John
