### ISSUE TITLE
ValueError: __len__() should return >= 0

### ISSUE THREAD

**Issue by tosonw** [NVIDIA-AI-IOT/torch2trt#323]
Traceback (most recent call last):
  File "/home/toson/softs/pycharm-2018.3/helpers/pydev/pydevd.py", line 1689, in <module>
    main()
  File "/home/toson/softs/pycharm-2018.3/helpers/pydev/pydevd.py", line 1683, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/toson/softs/pycharm-2018.3/helpers/pydev/pydevd.py", line 1083, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/toson/softs/pycharm-2018.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/e/myl/CenterNet/pth2trt/pth2trt.py", line 25, in <module>
    model_trt = torch2trt(model, [x])
  File "/home/toson/miniconda3/lib/python3.6/site-packages/torch2trt/torch2trt.py", line 377, in torch2trt
    outputs = module(*inputs)
  File "/home/toson/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/e/myl/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 471, in forward
    x = self.dla_up(x)
  File "/home/toson/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/e/myl/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 410, in forward
    ida(layers, len(layers) - i - 2, len(layers))
  File "/home/toson/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/e/myl/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 386, in forward
    layers[i] = node(layers[i] + layers[i - 1])
  File "/home/toson/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/e/myl/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 356, in forward
    x = self.conv(x)
  File "/home/toson/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/e/myl/CenterNet/src/lib/models/networks/DCNv2/dcn_v2.py", line 121, in forward
    offset = torch.cat((o1, o2), dim=1)
  File "/home/toson/miniconda3/lib/python3.6/site-packages/torch2trt/torch2trt.py", line 202, in wrapper
    converter['converter'](ctx)
  File "/home/toson/miniconda3/lib/python3.6/site-packages/torch2trt/converters/cat.py", line 14, in convert_cat
    trt_inputs = [trt_(ctx.network, i) for i in inputs]
  File "/home/toson/miniconda3/lib/python3.6/site-packages/torch2trt/converters/cat.py", line 14, in <listcomp>
    trt_inputs = [trt_(ctx.network, i) for i in inputs]
  File "/home/toson/miniconda3/lib/python3.6/site-packages/torch2trt/torch2trt.py", line 116, in trt_
    num_dim = len(t._trt.shape) # non-leaf tensors must already have _trt, get shape from that
ValueError: __len__() should return >= 0

**Comment by zhuhong** [comment]
dcn is not supported by torch2trt, as I think.

**Comment by czs1886** [comment]
Dcn requires plugins. Was there any unsupported layers?
