### ISSUE TITLE
AttributeError: module 'tensorrt' has no attribute '__version__'

### ISSUE THREAD

**Issue by danial880** [NVIDIA-AI-IOT/torch2trt#329]
I am using torch2trt on jetson nano. I have installed torch2trt with plugins using the official document. I am using the latest jetpack and version(7.1.0.16) of tensorrt. I get the following error

import torch2trt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dev/.virtualenvs/pytorch/lib/python3.6/site-packages/torch2trt/__init__.py", line 1, in <module>
    from .torch2trt import *
  File "/home/dev/.virtualenvs/pytorch/lib/python3.6/site-packages/torch2trt/torch2trt.py", line 5, in <module>
    from .calibration import TensorBatchDataset, DatasetCalibrator, DEFAULT_CALIBRATION_ALGORITHM
  File "/home/dev/.virtualenvs/pytorch/lib/python3.6/site-packages/torch2trt/calibration.py", line 5, in <module>
    if trt.__version__ >= '5.1':
AttributeError: module 'tensorrt' has no attribute '__version__'

**Comment by LearnedVector** [comment]
same error here on an ubuntu machine.

**Comment by lifefeel** [comment]
You may have `tensorrt.py` file on current directory. Delete this first and re-run.

**Comment by AmitNativ1984** [comment]
I had the same issue. Running on Jetpack 4.6.2. Had to update Tensorrt on host to 8.2.1.9 from 8.2.1.8.
* Here is a link to the patch from Nvidia: https://developer.nvidia.com/embedded/linux-tegra-r3272.
* Download and extract the [tar.gz](https://developer.nvidia.com/tensorrt-8219-patch-jetpack46-jetson-nx-16gbtargz).
* Follow the instructions in the install.md readme file to install it.
* Also make sure you have the Tensorrt csv file on host at: /etc/nvidia-container-runtime/host-files-container.d/tensorrt.csv
* If you don't you can add it with: 
`sudo apt-get install nvidia-container-csv-tensorrt`

**Comment by CNLiuZihao** [comment]
> You may have `tensorrt.py` file on current directory. Delete this first and re-run.

thanks
