### ISSUE TITLE
[Installation with plugins]: RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by baheytharwat** [NVIDIA-AI-IOT/torch2trt#344]
Hi,
First of all, I installed torch2trt without plugins according to the steps in the readme and it worked well ( I tested it with the example in the readme), then I realized that I need the version with plugins to use some operations. so, I tried to follow its instructions and I used " sudo apt-get install libprotobuf* protobuf-compiler ninja-build" then "sudo python3 setup.py install --plugins" and I got this error from the second command. 

```
running install
Checking .pth file support in /usr/local/lib/python3.6/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.6/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing torch2trt.egg-info/PKG-INFO
writing dependency_links to torch2trt.egg-info/dependency_links.txt
writing top-level names to torch2trt.egg-info/top_level.txt
reading manifest file 'torch2trt.egg-info/SOURCES.txt'
writing manifest file 'torch2trt.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying torch2trt/torch2trt.py -> build/lib.linux-x86_64-3.6/torch2trt
copying torch2trt/utils.py -> build/lib.linux-x86_64-3.6/torch2trt
copying torch2trt/__init__.py -> build/lib.linux-x86_64-3.6/torch2trt
copying torch2trt/test.py -> build/lib.linux-x86_64-3.6/torch2trt
copying torch2trt/module_test.py -> build/lib.linux-x86_64-3.6/torch2trt
copying torch2trt/converters/interpolate.py -> build/lib.linux-x86_64-3.6/torch2trt/converters
copying torch2trt/converters/ConvTranspose2d.py -> build/lib.linux-x86_64-3.6/torch2trt/converters
copying torch2trt/converters/avg_pool.py -> build/lib.linux-x86_64-3.6/torch2trt/converters
copying torch2trt/converters/transpose.py -> build/lib.linux-x86_64-3.6/torch2trt/converters
copying torch2trt/converters/unary.py -> build/lib.linux-x86_64-3.6/torch2trt/converters
copying torch2trt/converters/cat.py -> build/lib.linux-x86_64-3.6/torch2trt/converters
copying torch2trt/converters/Conv2d.py -> build/lib.linux-x86_64-3.6/torch2trt/converters
copying torch2trt/converters/BatchNorm2d.py -> build/lib.linux-x86_64-3.6/torch2trt/converters
copying torch2trt/converters/__init__.py -> build/lib.linux-x86_64-3.6/torch2trt/converters
copying torch2trt/converters/sum.py -> build/lib.linux-x86_64-3.6/torch2trt/converters
copying torch2trt/converters/permute.py -> build/lib.linux-x86_64-3.6/torch2trt/converters
copying torch2trt/converters/ConvTranspose.py -> build/lib.linux-x86_64-3.6/torch2trt/converters
copying torch2trt/converters/view.py -> build/lib.linux-x86_64-3.6/torch2trt/converters
copying torch2trt/converters/compare.py -> build/lib.linux-x86_64-3.6/torch2trt/converters
copying torch2trt/converters/batch_norm.py -> build/lib.linux-x86_64-3.6/torch2trt/converters
copying torch2trt/converters/stack.py -> build/lib.linux-x86_64-3.6/torch2trt/converters
copying torch2trt/converters/mul.py -> build/lib.linux-x86_64-3.6/torch2trt/converters
copying torch2trt/converters/Conv.py -> build/lib.linux-x86_64-3.6/torch2trt/converters
running build_ext
building 'plugins' extension
Emitting ninja build file /home/arl/Downloads/torch2trt/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] c++ -MMD -MF /home/arl/Downloads/torch2trt/build/temp.linux-x86_64-3.6/torch2trt/plugins/interpolate.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/aarch64-linux-gnu -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/include/python3.6m -c -c /home/arl/Downloads/torch2trt/torch2trt/plugins/interpolate.cpp -o /home/arl/Downloads/torch2trt/build/temp.linux-x86_64-3.6/torch2trt/plugins/interpolate.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=plugins -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: c++ -MMD -MF /home/arl/Downloads/torch2trt/build/temp.linux-x86_64-3.6/torch2trt/plugins/interpolate.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/aarch64-linux-gnu -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/include/python3.6m -c -c /home/arl/Downloads/torch2trt/torch2trt/plugins/interpolate.cpp -o /home/arl/Downloads/torch2trt/build/temp.linux-x86_64-3.6/torch2trt/plugins/interpolate.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=plugins -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
/home/arl/Downloads/torch2trt/torch2trt/plugins/interpolate.cpp:6:21: fatal error: NvInfer.h: No such file or directory
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    cmdclass={'build_ext': BuildExtension}
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 23, in run
    self.build()
  File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 49, in run
    _build_ext.run(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 174, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension


```
# Environment:
 PyTorch : '1.5.0+cu92'
torchvision 0.6
CUDA 10.0
TensorRT 7.0.0.11
Ubuntu 16.04

How can I solve this issue?

**Comment by baheytharwat** [comment]
I solved this issue by installing libnvinfer using this command:
sudo aptitude install libnvinfer7 libnvinfer-dev
