### ISSUE TITLE
[TensorRT] ERROR: (Unnamed Layer* 176) [Concatenation]: all concat input tensors must have the same dimensions except on the concatenati$n axi

### ISSUE THREAD

**Issue by ZehuaJiang** [NVIDIA-AI-IOT/torch2trt#347]
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
[TensorRT] ERROR: (Unnamed Layer* 176) [Concatenation]: all concat input tensors must have the same dimensions except on the concatenati$n axis
Traceback (most recent call last):
  File "main_small.py", line 108, in <module>
    model_trt = torch2trt(dbface, [dummy_input])
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py", line 436, in torch2trt
  File "/opt/malong/libs/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zehua/DBFace/model/DBFaceSmallH.py", line 263, in forward
    center = self.center(x)
  File "/opt/malong/libs/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zehua/DBFace/model/DBFaceSmallH.py", line 200, in forward
    x = self.ext(x)
  File "/opt/malong/libs/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zehua/DBFace/model/DBFaceSmallH.py", line 116, in forward
    x = self.conv(x)
  File "/opt/malong/libs/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py", line 218, in wrapper
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/converters/Conv2d.py", line 9, in convert_Conv2d
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py", line 132, in trt_
ValueError: __len__() should return >= 0

**Comment by jaybdub** [comment]
Hi ZehuaJiang,

Thanks for reaching out!

Are you able to share the model that you're attempting to convert?  Also the following information

1. PyTorch version
2. TensorRT version

Best,
John

**Comment by jxust01** [comment]
> Hi ZehuaJiang,
> 
> Thanks for reaching out!
> 
> Are you able to share the model that you're attempting to convert? Also the following information
> 
> 1. PyTorch version
> 2. TensorRT version
> 
> Best,
> John

Hi, I got the same problem, and my model is unet pytorch==1.1.0 TensorRT==7.0
