### ISSUE TITLE
[TensorRT] ERROR: (Unnamed Layer* 43) [Scale]: shift weights has count 256 but 1 was expected

### ISSUE THREAD

**Issue by Water2style** [NVIDIA-AI-IOT/torch2trt#366]
Please help,thanks
I CONVERT my trained tiny-yolov3  .pt

nvidia@ai:~/Desktop/PR/Deep$ python3 torch2rt.py 
begin to convert: 
Warning: Encountered known unsupported method torch.Tensor.expand_as
[TensorRT] ERROR: (Unnamed Layer* 43) [Scale]: shift weights has count 256 but 1 was expected
Traceback (most recent call last):
  File "torch2rt.py", line 90, in <module>
    model_trt = torch2trt(model, [x])
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py", line 436, in torch2trt
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nvidia/Desktop/PR/Deep/models.py", line 282, in forward
    x = module(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/activation.py", line 582, in forward
    return F.leaky_relu(input, self.negative_slope, self.inplace)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py", line 218, in wrapper
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/converters/activation.py", line 21, in convert_leaky_relu
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py", line 132, in trt_
ValueError: __len__() should return >= 0

**Comment by hushunda** [comment]
use_onnx=True
but that cause wrong if batch_size>1

**Comment by Water2style** [comment]
> use_onnx=True
> but that cause wrong if batch_size>1

I did some modify. But seems there are too many unsupprotted things and bugs. im about to give up.....

begin to convert: 
Warning: Encountered known unsupported method torch.sigmoid_
Warning: Encountered known unsupported method torch.sigmoid_
Traceback (most recent call last):
  File "torch2rt_Tyolo.py", line 101, in <module>
    model_trt = torch2trt(model, [x], int8_mode=True, int8_calib_dataset=dataset, int8_calib_algorithm=trt.CalibrationAlgoType.ENTROPY_CALIBRATION_2)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6-linux-aarch64.egg/torch2trt/torch2trt.py", line 440, in torch2trt
    ctx.mark_outputs(outputs, output_names)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6-linux-aarch64.egg/torch2trt/torch2trt.py", line 307, in mark_outputs
    trt_tensor = torch_output._trt
AttributeError: 'tuple' object has no attribute '_trt'

**Comment by hushunda** [comment]
兄弟，你先不要用int8_mode。

**Comment by jaybdub** [comment]
Hi All,

Thanks for reaching out!

Do you mind sharing a direct link to the Yolo model you're attempting to convert?

I may be able to directly spot the issue, or provide a workaround.

Best,
John

**Comment by Water2style** [comment]
> 兄弟，你先不要用int8_mode。

之前我没有加Int8这个模式一样的问题哈哈，感觉是我模型有问题

**Comment by Water2style** [comment]
> Hi All,
> 
> Thanks for reaching out!
> 
> Do you mind sharing a direct link to the Yolo model you're attempting to convert?
> 
> I may be able to directly spot the issue, or provide a workaround.
> 
> Best,
> John

Hi John，I used this model https://github.com/ggyybb/yolov3-tiny-deepsort-pytorch-cardetection/blob/master/models.py
Thank you

**Comment by zhulinzhang** [comment]
similar problem encountered here. I use CenterNet but change unsupported DCN layer to Deconvolution
