### ISSUE TITLE
Trying to convert torch.embedding get me an error

### ISSUE THREAD

**Issue by batrlatom** [NVIDIA-AI-IOT/torch2trt#404]
I am trying to convert model created by code from Karpathy: https://github.com/karpathy/minGPT and it uses embending layer which needs Long Tensor as an input. But torch2trt gives me an error TypeError: torch.int64 is not supported by tensorrt . I am using Jetson 4.4 with tensorrt 7.1+ which should convert it, but without any luck. Is there a possibility to make it work?

**Comment by Fan9** [comment]
@batrlatom Do you fixed this problem?

**Comment by miaodl** [comment]
> 
`Traceback (most recent call last):
  File "trt_embedding_long_capability.py", line 41, in <module>
    main(args)
  File "trt_embedding_long_capability.py", line 28, in main
    embedding_trt = torch2trt(embedding, [x])
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.3.0-py3.6.egg/torch2trt/torch2trt.py", line 551, in torch2trt
    ctx.add_inputs(inputs, input_names)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.3.0-py3.6.egg/torch2trt/torch2trt.py", line 407, in add_inputs
    dtype=torch_dtype_to_trt(torch_input.dtype),
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.3.0-py3.6.egg/torch2trt/torch2trt.py", line 38, in torch_dtype
_to_trt    raise TypeError("%s is not supported by tensorrt" % dtype)
TypeError: torch.int64 is not supported by tensorrt`


try to use newer docker image of L4T

https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-pytorch

2 step to fix this problem

1)  use this image

l4t-pytorch:r32.6.1-pth1.8-py3
PyTorch v1.8.0
torchvision v0.9.0
torchaudio v0.8.0

embedding layer of pt1.8 could support torch.int32.

2) convert your input tensort to torch.IntTensor()
