### ISSUE TITLE
[TensorRT] ERROR: (Unnamed Layer* 0) [Shuffle]: uninferred dimensions are not an exact divisor of input dimensions, so inferred dimension cannot be calculated

### ISSUE THREAD

**Issue by lxy443626128** [NVIDIA-AI-IOT/torch2trt#406]
when i run  model_trt = torch2trt(model, [x]):

[TensorRT] ERROR: (Unnamed Layer* 0) [Shuffle]: uninferred dimensions are not an exact divisor of input dimensions, so inferred dimension cannot be calculated

**Comment by lxy443626128** [comment]
[TensorRT] ERROR: (Unnamed Layer* 0) [Shuffle]: uninferred dimensions are not an exact divisor of input dimensions, so inferred dimension cannot be calculated
Traceback (most recent call last):
  File "test_rt.py", line 30, in <module>
    model_trt = torch2trt(model, [x],max_batch_size=8)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py", line 502, in torch2trt
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lixinyu07/beautyvideodemo/models.py", line 220, in forward
    base_out = self.base_model(input.view((-1, sample_len) + input.size()[-2:]))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/resnet.py", line 201, in forward
    x = self.layer1(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/resnet.py", line 112, in forward
    out += identity
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py", line 283, in wrapper
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/converters/add.py", line 14, in convert_add
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py", line 168, in broadcast_trt_tensors
ValueError: __len__() should return >= 0

**Comment by lxy443626128** [comment]
solved
