### ISSUE TITLE
Error when trying to convert segmentation model to TensorRT

### ISSUE THREAD

**Issue by michieljanssen97** [NVIDIA-AI-IOT/torch2trt#435]
Hi,

My segmentation architecture consists of a efficientnet-b2 encoder and FPN decoder. When trying to convert my model I stumble upon some errrors, see log below.

[TensorRT] ERROR: Parameter check failed at: ../builder/Network.cpp::addPoolingNd::747, condition: allDimsGtEq(windowSize, 1) && volume(windowSize) < MAX_KERNEL_DIMS_PRODUCT(nbSpatialDims)
Traceback (most recent call last):
  File "torchTRT.py", line 58, in <module>
    model_trt = torch2trt(model_w, [x], fp16_mode=True, strict_type_constraints=True)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py", line 536, in torch2trt
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "torchTRT.py", line 46, in forward
    return self.model(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/segmentation_models_pytorch/base/model.py", line 15, in forward
    features = self.encoder(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/segmentation_models_pytorch/encoders/efficientnet.py", line 59, in forward
    x = block(x, drop_connect_rate=drop_connect_rate)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/efficientnet_pytorch/model.py", line 85, in forward
    x_squeezed = F.adaptive_avg_pool2d(x, 1)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py", line 284, in wrapper
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/converters/adaptive_avg_pool2d.py", line 8, in convert_adaptive_avg_pool2d
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/converters/AdaptiveAvgPool2d.py", line 22, in convert_AdaptiveAvgPool2d
AttributeError: 'NoneType' object has no attribute 'stride'

Does someone encountered this error or can help me?

Thanks in advance,

Michiel

**Comment by zhouzw87** [comment]
I come the same problem, have you found solution?

**Comment by michieljanssen97** [comment]
> I come the same problem, have you found solution?

Hi Zhouzw87,

I didn’t manage to find a solution for it, neither NVIDIA.  I switched to another architecture :)
