### ISSUE TITLE
can not set int8_mode=True

### ISSUE THREAD

**Issue by kinghua2008** [NVIDIA-AI-IOT/torch2trt#446]
when I set int8_mode=True，it report error

here is code and report

```model = models.resnet50(pretrained=True).cuda().eval()
net = torchvision.models.resnet101(pretrained=False).cuda().eval()
x = torch.randn((1, 3, 320, 320))
model_trt = torch2trt(net, [x.cuda()], int8_mode=True)
with torch.no_grad():
    y_pt = net(x.cuda())[0]
y_trt = model_trt(x.cuda())[0]


Traceback (most recent call last):
  File "test.py", line 86, in <module>
    model_trt = torch2trt(net, [x.cuda()], int8_mode=True)
  File "/mnt/lib/python3.6/site-packages/torch2trt-0.1.0-py3.6-linux-aarch64.egg/torch2trt/torch2trt.py", line 560, in torch2trt
    engine = builder.build_cuda_engine(network)
RuntimeError: Method: read_calibration_cache was not overriden. Please provide an implementation for this method.
Segmentation fault (core dumped)
```

**Comment by jaybdub** [comment]
Hey @kinghua2008 ,

Thanks for reaching out!

Hmm, I'm not immediately sure what the cause of the issue is.

Do you mind sharing which version of TensorRT and PyTorch you are using?

Best,
John
