### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute '_trt'

### ISSUE THREAD

**Issue by maoni97** [NVIDIA-AI-IOT/torch2trt#484]
Hi, I trained a model from **MobileNet V3** and it worked well. In order to run it on the jetson nano, I tried to use the torch2trt to convert the model.

Then I got this error:

 ```
Traceback (most recent call last):
  File "trt_test.py", line 41, in <module>
    model_trt = torch2trt(model, [img], fp16_mode=True)

  File "/home/nanoproject/LaneDetect/torch2trt/torch2trt/torch2trt.py", line 531, in torch2trt
    ctx.mark_outputs(outputs, output_names)

  File "/home/nanoproject/LaneDetect/torch2trt/torch2trt/torch2trt.py", line 397, in mark_outputs
    trt_tensor = torch_output._trt

AttributeError: 'Tensor' object has no attribute '_trt'
```

**How could I find out which line caused this error?**

I saw that torch2trt has been tested on MobileNet V2 before. **So I suspect that this error is caused by the newly added modules of MobileNet V3.** I checked the modules in torch2trt.CONVERTERS, and there is no problem with other modules, **except for the newly added "hswish" and "hsigmoid" modules in MobileNet V3.**

But I'm not sure if there are other problems, so I want to upload my model. I don't know if anyone can see where the problem is.

Here is my original code:

```
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn import init

class hswish(nn.Module):
    def forward(self, x):
        out = x * F.relu6(x + 3, inplace=True) / 6
        return out


class hsigmoid(nn.Module):
    def forward(self, x):
        out = F.relu6(x + 3, inplace=True) / 6
        return out


class SeModule(nn.Module):
    def __init__(self, in_size, reduction=4):
        super(SeModule, self).__init__()
        self.se = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(in_size, in_size // reduction, kernel_size=1, stride=1, padding=0, bias=False),
            nn.BatchNorm2d(in_size // reduction),
            nn.ReLU(inplace=True),
            nn.Conv2d(in_size // reduction, in_size, kernel_size=1, stride=1, padding=0, bias=False),
            nn.BatchNorm2d(in_size),
            hsigmoid()
        )

    def forward(self, x):
        return x * self.se(x)


class Block(nn.Module):
    '''expand + depthwise + pointwise'''
    def __init__(self, kernel_size, in_size, expand_size, out_size, nolinear, semodule, stride):
        super(Block, self).__init__()
        self.stride = stride
        self.se = semodule

        self.conv1 = nn.Conv2d(in_size, expand_size, kernel_size=1, stride=1, padding=0, bias=False)
        self.bn1 = nn.BatchNorm2d(expand_size)
        self.nolinear1 = nolinear
        self.conv2 = nn.Conv2d(expand_size, expand_size, kernel_size=kernel_size, stride=stride, padding=kernel_size//2, groups=expand_size, bias=False)
        self.bn2 = nn.BatchNorm2d(expand_size)
        self.nolinear2 = nolinear
        self.conv3 = nn.Conv2d(expand_size, out_size, kernel_size=1, stride=1, padding=0, bias=False)
        self.bn3 = nn.BatchNorm2d(out_size)

        self.shortcut = nn.Sequential()
        if stride == 1 and in_size != out_size:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_size, out_size, kernel_size=1, stride=1, padding=0, bias=False),
                nn.BatchNorm2d(out_size),
            )

    def forward(self, x):
        out = self.nolinear1(self.bn1(self.conv1(x)))
        out = self.nolinear2(self.bn2(self.conv2(out)))
        out = self.bn3(self.conv3(out))
        if self.se != None:
            out = self.se(out)
        out = out + self.shortcut(x) if self.stride==1 else out
        return out

class Lane_detect_img(nn.Module):
    def __init__(self):
        super(Lane_detect_img, self).__init__()
        self.conv1 = nn.Conv2d(3, 3, kernel_size=5, stride=1, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(3)
        self.hs1 = hswish()

        self.bneck = nn.Sequential(
            Block(5, 3, 24, 24, nn.ReLU(inplace=True), SeModule(24), 1),    
            Block(5, 24, 48, 36, nn.ReLU(inplace=True), SeModule(36), 1),            
            Block(5, 36, 64, 48, nn.ReLU(inplace=True), None, 2),            
            Block(3, 48, 64, 64, hswish(), None, 2),                 
            Block(3, 64, 128, 64, hswish(), SeModule(64), 2),                
            Block(3, 64, 256, 128, hswish(), SeModule(128), 2),              
        )

        self.conv2 = nn.Conv2d(128, 128, kernel_size=3, stride=1, padding=0, bias=False)
        self.bn2 = nn.BatchNorm2d(128)
        self.hs2 = hswish()
        self.linear3 = nn.Linear(896, 64)        
        self.bn3 = nn.BatchNorm1d(64)
        self.hs3 = hswish()
        self.linear4 = nn.Linear(64, 1)
        self.init_params()

    def init_params(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                init.kaiming_normal_(m.weight, mode='fan_out')
                if m.bias is not None:
                    init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm2d):
                init.constant_(m.weight, 1)
                init.constant_(m.bias, 0)
            elif isinstance(m, nn.Linear):
                init.normal_(m.weight, std=0.001)
                if m.bias is not None:
                    init.constant_(m.bias, 0)

    def forward(self, x):
        out = self.hs1(self.bn1(self.conv1(x)))
        out = self.bneck(out)
        out = self.hs2(self.bn2(self.conv2(out)))
        out = out.view(out.size(0), -1)
        out = self.hs3(self.bn3(self.linear3(out)))
        out = self.linear4(out)
        return out

```

And if I find out where the problem is, how could I modified the code? I know there is a **@tensorrt_converter method**, but I'm not sure how to use it. **Could someone give me an example or any suggestions?**

By the way, I ran it in a docker container on jetson nano. Although I don't think this is an environmental issue, this is relevant information.

docker ( 19.03 )
python ( 3.6.9 )
torch ( 1.6.0 )
torchvision ( 0.7.0a0+6631b74 )
CUDA ( 10.2 )
opencv ( 4.1.1 )
numpy ( 1.17.2 )

**PLEASE HELP ME, THIS IS REALLY IMPORTANT TO ME!!! I WOULD BE VERY GRATEFUL TO EVERYONE WHO IS WILLING TO HELP!!!**

**Comment by Ursanon** [comment]
Did you solve it?

**Comment by igormusinov** [comment]
Hi @maoni97 , how did you solve it?

**Comment by fancoltran** [comment]
how did you resolve it?

**Comment by minha62** [comment]
Hi @maoni97 , how did you solve it??🥲😢
