### ISSUE TITLE
how to convert video net to trt when input is [batch, segment , c, h ,w]

### ISSUE THREAD

**Issue by ustcerlik** [NVIDIA-AI-IOT/torch2trt#497]
for video task, first i read data like [batch, segment, c, h ,w], then reshape as [batch*segment, c, h ,w], like function forward

                            def forward(self, inputs):
                                  assert len(inputs.size()) == 5, inputs.size()  # batch, segment, c, h, w
                                  bs, t, c, h, w = inputs.size()
                                  inputs = inputs.view(bs*t, c, h, w)
                                  x = self.backbone(inputs) 

raise Error:

[TensorRT] ERROR: [SHUFFLE #1] torch.Tensor.view(tensor(shape=[1, 3, 3, 384, 224], dtype=torch.float32), 3, 3, 384, 224): input and output volume mismatch. input volume is 774144 and output volume is 258048
[TensorRT] ERROR: Parameter check failed at: ../builder/Network.cpp::addScaleNd::737, condition: nbSpatialDims == 2 || nbSpatialDims == 3
Traceback (most recent call last):
  File "val2.py", line 208, in <module>
    main()
  File "val2.py", line 87, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "val2.py", line 121, in main_worker
    model_trt = torch2trt(model, [y], fp16_mode=True, max_batch_size=48)
  File "/opt/conda/lib/python3.6/site-packages/torch2trt-0.1.0-py3.6-linux-x86_64.egg/torch2trt/torch2trt.py", line 531, in torch2trt
    outputs = module(*inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/share/likuan/codes/ptvq/model/heads/trn.py", line 32, in forward
    embeddings = self.backbone(inputs)  # bs * t, dim
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/share/likuan/codes/ptvq/model/backbone2d/resnet.py", line 220, in forward
    return self._forward_impl(x)
  File "/share/likuan/codes/ptvq/model/backbone2d/resnet.py", line 204, in _forward_impl
    x = self.bn1(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/opt/conda/lib/python3.6/site-packages/torch2trt-0.1.0-py3.6-linux-x86_64.egg/torch2trt/torch2trt.py", line 285, in wrapper
    converter["converter"](ctx)
  File "/opt/conda/lib/python3.6/site-packages/torch2trt-0.1.0-py3.6-linux-x86_64.egg/torch2trt/converters/batch_norm.py", line 23, in convert_batch_norm_trt7
    output._trt = layer.get_output(0)
AttributeError: 'NoneType' object has no attribute 'get_output'

it works on image task when input shape is [batch, c,h,w]

p.s.: An inelegant solution for me: 
First i convert model.backbone to trt( resnet50), and then convert other blocks ,it works.

**Comment by momohuangsha** [comment]
How is this problem solved? I had the same problem

**Comment by yzycps** [comment]
same issue, did you solve it? @ustcerlik @momohuangsha
