### ISSUE TITLE
Seems that torch2trt doesn't support input of list of Tensor

### ISSUE THREAD

**Issue by smell-fishy** [NVIDIA-AI-IOT/torch2trt#50]
Hi, John.

My model takes a list of 5 Tensors as input.
And when,
model_trt = torch2trt(model, input),
here, input is a list of 5 Tensors.
It gives:
TypeError: forward() takes 2 positional arguments but 6 were given

**Comment by smell-fishy** [comment]
And then I modified my model with input as :

def forward(self, x1, x2, x3, x4, x5):

Then when I want to save the model, it gives:

Traceback (most recent call last):
  File "test_torch2trt.py", line 174, in <module>
    main(config)
  File "test_torch2trt.py", line 68, in main
    torch.save(model_resnet_ppm_trt.state_dict(), 'model_resnet_ppm.pth')
  File "/data/mawenxin/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 636, in state_dict
    hook_result = hook(self, destination, prefix, local_metadata)
  File "/data/mawenxin/anaconda3/lib/python3.7/site-packages/torch2trt/torch2trt.py", line 191, in _on_state_dict
    state_dict[prefix + 'engine'] = bytes(self.engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'

**Comment by bfortuner** [comment]
Running into the same issue. Did you figure this out?

**Comment by ma-siddiqui** [comment]
I am also facing the same problem. Anyone can elaborate?

**Comment by ma-siddiqui** [comment]
Hi,

Here is errors in my case: 

In function call torch2trt:

**engine = builder.build_cuda_engine(network)**

[TensorRT] ERROR: Unused Input: input_0
[TensorRT] ERROR: Unused Input: input_1

**Comment by BurkeyLai** [comment]
> Hi,
> 
> Here is errors in my case:
> 
> In function call torch2trt:
> 
> **engine = builder.build_cuda_engine(network)**
> 
> [TensorRT] ERROR: Unused Input: input_0
> [TensorRT] ERROR: Unused Input: input_1

Same issue QQ

**Comment by ma-siddiqui** [comment]
Hi,

I faced same issue and figured out after great struggle. In my case, i was having issue at group normalization. There were two implementations and my code was pointing to incomplete implementation of group normalization code. After fixing this code the invalid input issue ran away. 

Thanks, 
Muhammad Ajmal Siddiqui
