### ISSUE TITLE
import torch2trt error

### ISSUE THREAD

**Issue by whcjb** [NVIDIA-AI-IOT/torch2trt#509]
i have installed torch2trt, python3.6, but when import, error occurs. someone can help?
Python 3.6.11 | packaged by conda-forge | (default, Aug  5 2020, 20:09:42)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
'>>>' from torch2trt import torch2trt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/converters/__init__.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/converters/floordiv.py", line 6, in <module>
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py", line 589, in tensorrt_converter
  File "<string>", line 1, in <module>
AttributeError: type object 'Tensor' has no attribute '__ifloordiv__'

**Comment by whcjb** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/cfs/yanpeifa/torch2trt-master/torch2trt/__init__.py", line 2, in <module>
    from .converters import *
  File "/media/cfs/yanpeifa/torch2trt-master/torch2trt/converters/__init__.py", line 29, in <module>
    from .floordiv import *
  File "/media/cfs/yanpeifa/torch2trt-master/torch2trt/converters/floordiv.py", line 6, in <module>
    @tensorrt_converter('torch.Tensor.__ifloordiv__')
  File "/media/cfs/yanpeifa/torch2trt-master/torch2trt/torch2trt.py", line 589, in tensorrt_converter
    method_impl = eval('copy.deepcopy(module.%s)' % qual_name)
  File "<string>", line 1, in <module>
AttributeError: type object 'Tensor' has no attribute '__ifloordiv__'

**Comment by whcjb** [comment]
![image](https://user-images.githubusercontent.com/11767995/109120239-ad2f2780-7780-11eb-8301-f7bf7baa220b.png)

**Comment by whcjb** [comment]
it's pytorch version problem, it is solved by install pytorch1.6.
