### ISSUE TITLE
Multi input model conversion

### ISSUE THREAD

**Issue by jjinCode** [NVIDIA-AI-IOT/torch2trt#522]
https://github.com/NVIDIA-AI-IOT/torch2trt/issues/33#issuecomment-517163026
In this reply, torch2trt should support conversion for multi input model.
But my model which has 6 input tensor (all input tensors have a different size) occurs error.

Is it possible to convert model that has a more than 4 inputs?

**Comment by jaybdub** [comment]
Hi jjinCod,

Thanks for reaching out!

torch2trt doesn't impose any strict limit on the number of inputs, but it's possible there is another issue you're encountering or this causes problems downstream.

Are you able to share the model you're attempting to convert?  Or some similar steps to reproduce this issue?

Best,
John

**Comment by jjinCode** [comment]
Thanks for your reply @jaybdub !!!

I try to usetorch2trt for converting model named 'monodepth2'
repo : https://github.com/nianticlabs/monodepth2

It is consist of 2 part, encoder and decoder.
The input of encoder is just color image, so it has no problem.

But decoder has input that list of five 4D tensors which has different size.
I tried this command model_decoder_trt = torch2trt.torch2trt(decoder, [x1, x2, x3, x4, x5])
and returned that error message : forward() takes from 2 to 3 positional arguments but 6 were given

I suspect that decoder's input is 'list including 5 tensors' not separated 5 tensors...

**Comment by jjinCode** [comment]
Hi, @jaybdub 
I still wonder that is it possible to convert model which take python data structure list as network's input with torch2trt.
If it is impossible, I try to change network architecture...ㅜㅜ

**Comment by jaybdub** [comment]
Hi jjinCode,

Apologies for the delay responding.  

While I believe this should work, it's very possible there is a bug.  I'm going to take a more detailed look at the repository you shared to see what is causing the issue.

I'll keep you posted here.

Best,
John

**Comment by pepinu** [comment]
@jjinCode multiple inputs can always be circumvented by rewriting the forward function in your model. Just pass everything as one tensor and unpack it in the first line.

**Comment by jaybdub** [comment]
As @pepinu mentioned, you can probably work around this issue by reformatting the forward function, or wrapping it.

I just tested a method for wrapping MonoDepth2.   Perhaps there are other cleaner ways.  Admittedly, it would be nice if torch2trt implicitly handled dictionary outputs, but I'm not yet sure if this has any adverse impact.


Wrap dictionary model

```python
import networks
import torch

class DecoderWrapper(torch.nn.Module):
    
    def __init__(self):
        super().__init__()
        self.decoder = depth_decoder = networks.DepthDecoder(
            num_ch_enc=encoder.num_ch_enc, scales=range(4))
        
    def forward(self, *inputs):
        # take arguments in form decoder(tensor0, tensor1, ...)
        out = self.decoder(inputs)
        
        # extract dictionary items and sort highest -> lowest
        out_list = [(key[1], tensor) for key, tensor in out.items()]
        out_list = sorted(out_list, key=lambda x: x[0])
        out_list = [entry[1] for entry in out_list]
        
        # return like return out4, out3, out2, out1 .. 
        return tuple(out_list)
    
class DecoderUnwrapper(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.wrapper = DecoderWrapper()
        
    def forward(self, out):
        out_list = self.wrapper(*out)
        out_dict = {('disp', idx): tensor for idx, tensor in enumerate(out_list)}
        return out_dict
```

verify wrapper/unwrapper matches original decoder

```python

encoder = networks.ResnetEncoder(18, False).cuda().eval()

depth_decoder = networks.DepthDecoder(
    num_ch_enc=encoder.num_ch_enc, scales=range(4)).cuda().eval()

unwrapper = DecoderUnwrapper().cuda().eval()

data = torch.randn([1, 3, 640, 192]).cuda()

out = encoder(data)

print(unwrapper(out)[('disp', 1)].shape)
print(depth_decoder(out)[('disp', 1)].shape)
```

optimize internal wrapper with torch2trt

```python
from torch2trt import torch2trt

# convert wrapper
wrapper_trt = torch2trt(unwrapper.wrapper, out)

# replace wrapper in decoder
unwrapper.wrapper = wrapper_trt

print(unwrapper.wrapper)  # should be TRTModule

print(unwrapper(out)[('disp', 1)].shape)
print(depth_decoder(out)[('disp', 1)].shape)
```

Currently, I'm seeing a discrepancy in the actual values now, but I'm using random weights.   If you see a discrepancy in output, I'm interested in understanding this, it may be a bug in one of the converters which we could address.

Please let me know if this helps or you run into issues. 

Best,
John

**Comment by jjinCode** [comment]
Thanks @pepinu , @jaybdub !!!

I'll try to convert the way you advised me.
And I'll share the results.

**Comment by daodao9801** [comment]
> As @pepinu mentioned, you can probably work around this issue by reformatting the forward function, or wrapping it.
> 
> I just tested a method for wrapping MonoDepth2. Perhaps there are other cleaner ways. Admittedly, it would be nice if torch2trt implicitly handled dictionary outputs, but I'm not yet sure if this has any adverse impact.
> 
> Wrap dictionary model
> 
> ```python
> import networks
> import torch
> 
> class DecoderWrapper(torch.nn.Module):
>     
>     def __init__(self):
>         super().__init__()
>         self.decoder = depth_decoder = networks.DepthDecoder(
>             num_ch_enc=encoder.num_ch_enc, scales=range(4))
>         
>     def forward(self, *inputs):
>         # take arguments in form decoder(tensor0, tensor1, ...)
>         out = self.decoder(inputs)
>         
>         # extract dictionary items and sort highest -> lowest
>         out_list = [(key[1], tensor) for key, tensor in out.items()]
>         out_list = sorted(out_list, key=lambda x: x[0])
>         out_list = [entry[1] for entry in out_list]
>         
>         # return like return out4, out3, out2, out1 .. 
>         return tuple(out_list)
>     
> class DecoderUnwrapper(torch.nn.Module):
>     def __init__(self):
>         super().__init__()
>         self.wrapper = DecoderWrapper()
>         
>     def forward(self, out):
>         out_list = self.wrapper(*out)
>         out_dict = {('disp', idx): tensor for idx, tensor in enumerate(out_list)}
>         return out_dict
> ```
> 
> verify wrapper/unwrapper matches original decoder
> 
> ```python
> encoder = networks.ResnetEncoder(18, False).cuda().eval()
> 
> depth_decoder = networks.DepthDecoder(
>     num_ch_enc=encoder.num_ch_enc, scales=range(4)).cuda().eval()
> 
> unwrapper = DecoderUnwrapper().cuda().eval()
> 
> data = torch.randn([1, 3, 640, 192]).cuda()
> 
> out = encoder(data)
> 
> print(unwrapper(out)[('disp', 1)].shape)
> print(depth_decoder(out)[('disp', 1)].shape)
> ```
> 
> optimize internal wrapper with torch2trt
> 
> ```python
> from torch2trt import torch2trt
> 
> # convert wrapper
> wrapper_trt = torch2trt(unwrapper.wrapper, out)
> 
> # replace wrapper in decoder
> unwrapper.wrapper = wrapper_trt
> 
> print(unwrapper.wrapper)  # should be TRTModule
> 
> print(unwrapper(out)[('disp', 1)].shape)
> print(depth_decoder(out)[('disp', 1)].shape)
> ```
> 
> Currently, I'm seeing a discrepancy in the actual values now, but I'm using random weights. If you see a discrepancy in output, I'm interested in understanding this, it may be a bug in one of the converters which we could address.
> 
> Please let me know if this helps or you run into issues.
> 
> Best,
> John

It might be something about the reflection padding ops. Like others found here
https://github.com/nianticlabs/monodepth2/issues/38
"reflection padding is not supported in TensorRT (only zero-padding is included)"

Would you mind having a check on that? Thx.

**Comment by jjinCode** [comment]
Hi, @daodao9801 
I changed some configuration.
1. I changed decoder's input and out to just multiple tensors
2. I changed reflection mode from ReflectionPad2d to ZeroPad2d

But I got this error

Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Error: decoder_trt.gv: syntax error in line 66 near '''
Traceback (most recent call last):
  File "depth_inference_for_trt.py", line 292, in <module>
    inference(options.parse())
  File "depth_inference_for_trt.py", line 141, in inference
    draw2.render("decoder_trt.gv", view=False)	
  File "/home/jinho-sesol/anaconda3/envs/trt/lib/python3.6/site-packages/graphviz/files.py", line 245, in render
    quiet=quiet)
  File "/home/jinho-sesol/anaconda3/envs/trt/lib/python3.6/site-packages/graphviz/backend.py", line 225, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "/home/jinho-sesol/anaconda3/envs/trt/lib/python3.6/site-packages/graphviz/backend.py", line 186, in run
    output=out, stderr=err)
graphviz.backend.CalledProcessError: Command '['dot', '-Kdot', '-Tpdf', '-O', 'decoder_trt.gv']' returned non-zero exit status 1. [stderr: b"Error: decoder_trt.gv: syntax error in line 66 near '''\n"]

I think I have some problem
1. Even though I changed to zeropad. there are some problem about conversion of decoder
2. when I tried to render decoder_trt.gv using graphviz, it occur above error...
