### ISSUE TITLE
unable to import torch2trt 

### ISSUE THREAD

**Issue by shubhamgajbhiye1994** [NVIDIA-AI-IOT/torch2trt#543]
>>> import torch2trt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/darkshadow/anaconda3/envs/new_tf/lib/python3.6/site-packages/torch2trt-0.2.0-py3.6.egg/torch2trt/__init__.py", line 1, in <module>
  File "/home/darkshadow/anaconda3/envs/new_tf/lib/python3.6/site-packages/torch2trt-0.2.0-py3.6.egg/torch2trt/torch2trt.py", line 2, in <module>
ModuleNotFoundError: No module named 'tensorrt'

**Comment by LianShuaiLong** [comment]
you should configure your tensorrt correctly!
you can pull tensorrt docker from : https://ngc.nvidia.com/catalog/containers/nvidia:tensorrt

**Comment by shubhamgajbhiye1994** [comment]
ok,let me try ...
