### ISSUE TITLE
TypeError: add_constant(): incompatible function arguments.

### ISSUE THREAD

**Issue by sinuku** [NVIDIA-AI-IOT/torch2trt#544]
Hi!

I’m trying to make an tensorrt engine using torch2trt.
I trained a custom dataset using YOLACT and mobilenetv2.

My code is like:
```
import torch
from torch2trt import torch2trt
from torchvision.models.mobilenet import MobileNetV2

model = MobileNetV2()
model.load_state_dict(torch.load('weights/yolact_mobilenetv2_custom_2941_50000.pth'), strict=False)
        
x = torch.ones((1, 3, my_image_size, my_image_size)).cuda()
model_trt = torch2trt(model, [x], fp16_mode=True, strict_type_constraints=True)

torch.save(model_trt.state_dict(), my_module_path)
```

However I ran into the below problem:
```
WARNING: Unsupported numpy data type. Cannot implicitly convert to tensorrt.Weights.
Traceback (most recent call last):
  File "/home/sensor/Desktop/yolact/yolact.py", line 1530, in to_tensorrt
    model_trt = torch2trt(model, [x], fp16_mode=True, strict_type_constraints=True)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.2.0-py3.6-linux-x86_64.egg/torch2trt/torch2trt.py", line 542, in torch2trt
    outputs = module(*inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/mobilenet.py", line 171, in forward
    return self._forward_impl(x)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/mobilenet.py", line 164, in _forward_impl
    x = self.features(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/batchnorm.py", line 111, in forward
    self.num_batches_tracked = self.num_batches_tracked + 1
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.2.0-py3.6-linux-x86_64.egg/torch2trt/torch2trt.py", line 289, in wrapper
    converter["converter"](ctx)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.2.0-py3.6-linux-x86_64.egg/torch2trt/converters/add.py", line 13, in convert_add
    input_a_trt, input_b_trt = add_missing_trt_tensors(ctx.network, [input_a, input_b])
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.2.0-py3.6-linux-x86_64.egg/torch2trt/torch2trt.py", line 157, in add_missing_trt_tensors
    t._trt = network.add_constant(shape, weight).get_output(0)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.2.0-py3.6-linux-x86_64.egg/torch2trt/torch2trt.py", line 353, in wrapper
    ret = attr(*args, **kwargs)
TypeError: add_constant(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.INetworkDefinition, shape: tensorrt.tensorrt.Dims, weights: tensorrt.tensorrt.Weights) -> tensorrt.tensorrt.IConstantLayer

Invoked with: <tensorrt.tensorrt.INetworkDefinition object at 0x7fe2787810a0>, (), array(1)
```

what's the problem??

**Comment by tucachmo2202** [comment]
You should try to add `model_trt = torch2trt(model,eval().cuda(), [x], fp16_mode=True, strict_type_constraints=True)
`
