### ISSUE TITLE
Slicing operation doesn't work properly

### ISSUE THREAD

**Issue by taikiinoue45** [NVIDIA-AI-IOT/torch2trt#564]
### Environment
- Jetson AGX Xavier
- Ubuntu 18.04 LTS
- Cuda 10.2
- Python 3.6.9 
- Torch 1.6.0
- Torch2TRT 0.1.0
- Torchvision 0.7.0
- TensorRT 7.1.3.0

### Script (run.py)

```python
import torch
import torch.nn as nn
from torch import Tensor
from torch2trt import torch2trt
from torch.nn import Module


class ToyModel(Module):
    def __init__(self) -> None:

        super().__init__()
        self.conv = nn.Conv2d(3, 256, kernel_size=3, stride=1, padding=1)
        self.idxs = torch.randint(0, 256, (100,)).cuda()

    def forward(self, x0: Tensor, y: Tensor) -> Tensor:

        x1 = self.conv(x0)           # x1.shape -> (1, 256, 56, 56)
        x2 = x1[:, self.idxs, :, :]  # x2.shape -> (1, 100, 56, 56)
        x3 = x2 - y                  # x3.shape -> (1, 100, 56, 56)
        return x3


if __name__ == "__main__":

    x = torch.ones(1, 3, 56, 56).cuda()
    y = torch.ones(1, 100, 56, 56).cuda()

    model = ToyModel().cuda()
    z = model(x, y)
    print(f"z.shape: {z.shape}")

    model_trt = torch2trt(model, [x, y], fp16_mode=True)
    z_trt = model_trt(x, y)
    print(f"z_trt.shape: {z_trt.shape}")

```

### Command & Error Messages

```
$ python3 sandbox0.py 
z.shape: torch.Size([1, 100, 56, 56])
[TensorRT] ERROR: [ELEMENTWISE #1] torch.Tensor.__sub__(tensor(shape=[1, 100, 56, 56], dtype=torch.float32), tensor(shape=[1, 100, 56, 56], dtype=torch.float32)): elementwise inputs must have same dimensions or follow broadcast rules (input dimensions were [256,56,56] and [100,56,56]).
[TensorRT] ERROR: Could not compute dimensions for output_0, because the network is not valid.
[TensorRT] ERROR: Network validation failed.
Traceback (most recent call last):
  File "sandbox0.py", line 33, in <module>
    z_trt = model_trt(x, y)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py", line 451, in forward
    idx = self.engine.get_binding_index(output_name)
AttributeError: 'NoneType' object has no attribute 'get_binding_index'
```

**Comment by taikiinoue45** [comment]
Before calling torch2trt, the model works properly, and returns `z.shape: torch.Size([1, 100, 56, 56])`. However, model_trt(x, y) returns the error due to slicing operation `x1[:, self.idxs, :, :]`. I think the following url is the similar issue. Is it still not solved?

https://github.com/NVIDIA-AI-IOT/torch2trt/issues/234

**Comment by taikiinoue45** [comment]
https://github.com/NVIDIA-AI-IOT/torch2trt/issues/234
