### ISSUE TITLE
Custom layer converter is not called 

### ISSUE THREAD

**Issue by westfly** [NVIDIA-AI-IOT/torch2trt#589]
Running Env

```
OS centos7
CUDA 11.0
TensorRT 7.2.2.2
cuDNN8.0
pytorch 1.7.1
```

when run the snipped code, it will print "################" show that **convert_ReLU** was called

```python
import tensorrt as trt
from torch2trt import tensorrt_converter
import torch
from torch2trt import torch2trt
from torchvision.models.alexnet import alexnet

def check_alexnet():
    # create some regular pytorch model...
    model = alexnet(pretrained=True).eval().cuda()
    # create example data
    x = torch.ones((1, 3, 224, 224)).cuda()
    # convert to TensorRT feeding sample data as input
    print("Graph {}\n".format(torch.jit.script(model).graph))
    model_trt = torch2trt(model, [x])
    y = model(x)
    y_trt = model_trt(x)
    print("Graph@TRT {}\n".format(model_trt.graph))

    # check the output against PyTorch
    print(torch.max(torch.abs(y - y_trt)))
    torch.save(model.state_dict(), 'data/alexnet.pth')
    torch.save(model_trt.state_dict(), 'data/alexnet_trt.pth')

@tensorrt_converter('torch.nn.ReLU.forward')
def convert_ReLU(ctx):
    input = ctx.method_args[1]
    output = ctx.method_return
    print("################ tx {}########", ctx.torch2trt_kwargs)
    layer = ctx.network.add_activation(
        input=input._trt, type=trt.ActivationType.RELU)
    output._trt = layer.get_output(0)
check_alexnet()
```

but **Sparse.forward** registered without calling, not same as **convert_ReLU**

```python

def load_ts_model(model_path):
    model = torch.jit.load(model_path).eval();
    x = torch.ones((1,3,224,224))
    print("Graph {}\n".format(model.graph))
    model_trt = torch2trt(model, [x])
    y_trt = model_trt(x)

@tensorrt_converter('model.Sparse.forward')
def convert_Sparse(ctx):
    output = ctx.method_return
    print("################ tx {}########", ctx.torch2trt_kwargs)
    output._trt = ctx.method_args[1]
load_ts_model("data/ali.pt")

```
data/ali.pt was generate with script model/model.py

```python
import os
import time
import torch

import torchvision
class Sparse(torch.nn.Module):

    def __init__(self, embedding_size):
        super().__init__()
        self._embedding_size =  embedding_size
        self._output = torch.zeros((4, self._embedding_size))

    def forward(self, x):
        return self._output


class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.sparse = Sparse(100)
        self.linear = torch.nn.Linear(100, 200)

    def forward(self, x):
        y = self.sparse(x)
        return self.linear(y)
if __name__ == '__main__':
    model = torch.jit.script(Model())
    model.save("data/ali.pt")
```

**Comment by jaybdub** [comment]
Hi @westfly,

Thanks for reaching out!

This is likely because torch2trt cannot resolve the name of your custom module.

For layers defined in your own modules, it might work better to try passing the function reference, rather than the absolute name.  For example,

```python3
from torch2trt import tensorrt_converter
from model import Sparse

@tensorrt_converter(Sparse.forward)
def convert_sparse(ctx):
    ...
```

Instead of 

```python3
@tensorrt_converter('Sparse.forward')
def convert_sparse(ctx):
    ...
```

Please let me know if this helps or you run into any issues.

Best,
John

**Comment by westfly** [comment]
still don't work.
I also Upgrade version to TensorRT to 7.2.3 and pytorch 1.8.1

```
Traceback (most recent call last):
  File "models/trt_model.py", line 46, in <module>
    load_ts_model("../data/ali.pt")
  File "models/trt_model.py", line 38, in load_ts_model
    model_trt = torch2trt(model, [x])
  File "torch2trt/python-env/.pyenv/versions/3.6.13/lib/python3.6/site-packages/torch2trt-0.2.0-py3.6.egg/torch2trt/torch2trt.py", line 556, in torch2trt
    ctx.mark_outputs(outputs, output_names)
  File "torch2trt/python-env/.pyenv/versions/3.6.13/lib/python3.6/site-packages/torch2trt-0.2.0-py3.6.egg/torch2trt/torch2trt.py", line 418, in mark_outputs
    trt_tensor = torch_output._trt
AttributeError: 'Tensor' object has no attribute '_trt'
```

```python
import tensorrt as trt
from torch2trt import tensorrt_converter
import torch
from torch2trt import torch2trt
from torchvision.models.alexnet import alexnet
from model import Sparse

def check_alexnet():
    # create some regular pytorch model...
    model = alexnet(pretrained=True).eval().cuda()
    # create example data
    x = torch.ones((1, 3, 224, 224)).cuda()
    # convert to TensorRT feeding sample data as input
    print("Graph {}\n".format(torch.jit.script(model).graph))
    model_trt = torch2trt(model, [x])
    y = model(x)
    y_trt = model_trt(x)
    print("Graph@TRT {}\n".format(model_trt.graph))

    # check the output against PyTorch
    print(torch.max(torch.abs(y - y_trt)))
    torch.save(model.state_dict(), 'data/alexnet.pth')
    torch.save(model_trt.state_dict(), 'data/alexnet_trt.pth')

@tensorrt_converter('torch.nn.ReLU.forward')
def convert_ReLU(ctx):
    input = ctx.method_args[1]
    output = ctx.method_return
    print("################ tx {}########", ctx.torch2trt_kwargs)
    layer = ctx.network.add_activation(
        input=input._trt, type=trt.ActivationType.RELU)
    output._trt = layer.get_output(0)

def load_ts_model(model_path):
    model = torch.jit.load(model_path).eval();
    x = torch.ones((1,3,224,224))
    print("Graph {}\n".format(model.graph))
    model_trt = torch2trt(model, [x])
    y_trt = model_trt(x)

@tensorrt_converter(Sparse.forward)
def convert_Sparse(ctx):
    output = ctx.method_return
    print("################ tx {}########", ctx.torch2trt_kwargs)
    output._trt = ctx.method_args[1]
load_ts_model("../data/ali.pt")
#check_alexnet()
```
