### ISSUE TITLE
torch.topk support

### ISSUE THREAD

**Issue by JWLee89** [NVIDIA-AI-IOT/torch2trt#598]
Hi, 

I have tried to add topk support, but for some reason, I am getting the notorious error: 

```
AttributeError: 'torch.return_types.topk' object has no attribute '_trt'
```

I have checked to see whether the `input_tensor` has `_trt` property and it does. If anybody has any insight into the root cause of this issue, that would be very much appreciated. 

Below is the code 

```
@tensorrt_converter("torch.Tensor.topk")
@tensorrt_converter("torch.topk")
def convert_topk(ctx):
    
    input_tensor = ctx.method_args[0]
    # The K in "topk"
    top_k = ctx.method_args[1]
    output = ctx.method_return

    # Handle optional axis argument
    has_axis = len(ctx.method_args) > 2
    if has_axis:
        axis = ctx.method_args[2]
    else:
        axis = 0

    # input_trt = broadcast_trt_tensors(ctx.network, [input_trt], len(output[0].shape) - 1)
    # input_layer = ctx.get
    layer = ctx.network.add_topk(input_tensor._trt, trt.TopKOperation.MAX, top_k, axis)

    # Has two outputs: (Tensor, LongTensor). 
    # LongTensor is the corresponding indices to the topk operation
    output._trt = layer.get_output(0), layer.get_output(1)
```

Thanks in advance!

**Comment by jaybdub** [comment]
Hi @JWLee89 ,

Thanks for reaching out!

It looks like ``torch.topk`` returns a tuple of tensors.  You'll likely need to set the ``_trt`` attribute for each tensor separately rather than the returned tuple. 
 Could you try modifying your converter to something like

```python
...
    output_a, output_b = ctx.method_return
...
    output_a._trt, output_b._trt = layer.get_output(0), layer.get_output(1)
...
```

Please let me know if this helps or you run into any issues.  FYI - if you end up getting this to work, I'd be happy to review a PR.

Best,
John

**Comment by JWLee89** [comment]
@jaybdub Hi John, 

Your feedback was very helpful and made perfect sense. I wasn't aware of the fact that `ctx.method_return` could return a `tuple`. But after you mentioned it, I did as you suggested and got over the initial issue with the output tensor not having the property `_trt`.

I am currently attempting to resolve the final hurdle, which is the fact that the PyTorch implementation of `torch.topk` returns a two tuple with the following specification:

1. A tensor made up of the top-k values (type - same as input-tensor) 
2. A tensor with the corresponding indices to the top-k values (type - LongTensor: **64bit int**)

I believe that TensorRT only supports 32bit data types and since topk returns a LongTensor as part of its output, this error is being thrown. 

To create a valid TensorRT I attempted the following: 

```
output_a, output_b = ctx.method_return

topk_layer = ctx.network.add_topk(input_tensor._trt, trt.tensorrt.TopKOperation.MAX, top_k, axis)

# Second output of the two-tuple is int64 type, which is not supported by TensorRT 
# Therefore, I set the output_type to int32 to implicitly downcast. 
# Not sure if this is the recommended approach
topk_layer.set_output_type(1, trt.int32)

# I also tried incorporating identity layers to downcast, but so far no luck
# indices_identity = ctx.network.add_identity(indices)

output_a._trt, output_b._trt = topk_layer.get_output(0), topk_layer.get_output(1)
```

Is there a way to downcast the output of `torch.int64` to `trt.int32`. 

I also wrote a custom layer that casts PyTorch tensors using `.float()` and `.int()`. If there is a way to retrieve the PyTorch output, would it be possible to do the casting by calling `.int()` on the PyTorch tensors prior to the `output_a._trt, output_b._trt = topk_layer.get_output(0), topk_layer.get_output(1)` call?


Although I don't think it will be of much help, I also included the stacktrace just in case. 

```
Traceback (most recent call last):
  File "test_top_k.py", line 233, in <module>
    test_topk()
  File "test_top_k.py", line 207, in test_topk
    trt_model = torch2trt.torch2trt(net, [input_tensor])
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.3.0-py3.6.egg/torch2trt/torch2trt.py", line 556, in torch2trt
    ctx.mark_outputs(outputs, output_names)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.3.0-py3.6.egg/torch2trt/torch2trt.py", line 421, in mark_outputs
    trt_tensor.dtype = torch_dtype_to_trt(torch_output.dtype)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.3.0-py3.6.egg/torch2trt/torch2trt.py", line 38, in torch_dtype_to_trt
    raise TypeError("%s is not supported by tensorrt" % dtype)
TypeError: torch.int64 is not supported by tensorrt
```

Thank you for your time. 

Best regards,
Jay
