### ISSUE TITLE
Not able to install torch2trt in windows10

### ISSUE THREAD

**Issue by rgkannan676** [NVIDIA-AI-IOT/torch2trt#613]
Hi all,

I tried to install torch2trt following the steps

```
git clone https://github.com/NVIDIA-AI-IOT/torch2trt
cd torch2trt
sudo python setup.py install --plugins

```

and go the following error:

```
D:\torch2trt\torch2trt\plugins\interpolate.cpp(6): fatal error C1083: Cannot open include file: 'NvInfer.h': No such file or directory
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\torch\utils\cpp_extension.py", line 1666, in _run_ninja_build
    subprocess.run(
  File "C:\Users\User\Anaconda3\envs\py_env\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    setup(
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\torch\utils\cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\torch\utils\cpp_extension.py", line 682, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\torch\utils\cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\torch\utils\cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Comment by rgkannan676** [comment]
I copied the files as suggested in https://github.com/vujadeyoon/TensorRT-Torch2TRT. 

Got the following issue after that.

```
D:\torch2trt\torch2trt\plugins\group_norm.cpp(204): note: while trying to match the argument list '(void *, std::vector<long,std::allocator<long>>, torch2trt::GroupNormPlugin::enqueue::<lambda_b7e180e89a72219eea45efeaf6bb1309>, c10::TensorOptions)'
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\torch\utils\cpp_extension.py", line 1666, in _run_ninja_build
    subprocess.run(
  File "C:\Users\User\Anaconda3\envs\py_env\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    setup(
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\torch\utils\cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\User\Anaconda3\envs\py_env\lib\distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\torch\utils\cpp_extension.py", line 682, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\torch\utils\cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\Users\User\Anaconda3\envs\py_env\lib\site-packages\torch\utils\cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Comment by nicken** [comment]
I solved it；
you must  modify the`setup.py` file, let it known where is you tensorRT path of include and lib


I modified it to look like this
```python
def trt_inc_dir():
    return "/usr/local/TensorRT/include"

def trt_lib_dir():
    return "/usr/local/TensorRT/lib"
```
