### ISSUE TITLE
AdaptivaAvgPool2d :  'NoneType' object has no attribute 'stride'

### ISSUE THREAD

**Issue by aoaforever** [NVIDIA-AI-IOT/torch2trt#643]
Hello, I have a problem. Did the torch2trt support to convert AdaptivaAvgPool2d? I found the source code for convert AdaptiveAvgPool2d, but it doesn't work.

class net(nn.Module):
    def __init__(self):
        super(net, self).__init__()
        self.global_aver_polling=nn.AdaptiveAvgPool2d((1,1))
    def forward(self,x):
        out=self.global_aver_polling(x)
        return out
if __name__ == '__main__':
    img = torch.randn(1, 32, 640, 360).cuda()
    net2 = net().cuda().eval()
    net2_trt=torch2trt(net2,[img])
    with torch.no_grad():
            net2_trt(img)

Traceback (most recent call last):
  File "test_conv_time.py", line 154, in <module>
    net2_trt=torch2trt(net2,[img])
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.3.0-py3.6-linux-aarch64.egg/torch2trt/torch2trt.py", line 553, in torch2trt
    outputs = module(*inputs)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "test_conv_time.py", line 102, in forward
    out=self.global_aver_polling(x)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.3.0-py3.6-linux-aarch64.egg/torch2trt/torch2trt.py", line 300, in wrapper
    converter["converter"](ctx)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.3.0-py3.6-linux-aarch64.egg/torch2trt/converters/AdaptiveAvgPool2d.py", line 22, in convert_AdaptiveAvgPool2d
    **_layer.stride = stride_**
AttributeError: 'NoneType' object has no attribute 'stride'

**Comment by aoaforever** [comment]
My task is the imgae superresolution, but I now notice that this torch2trt doesn't support dynamic input.
please see this link: https://github.com/NVIDIA-AI-IOT/torch2trt/issues/317

And no offense, I will try this repositories : https://github.com/grimoire/torch2trt_dynamic

**Comment by superddr** [comment]
I have the same problem

**Comment by RolandGao** [comment]
I have the same problem. I think it fails when the input size is too big

**Comment by fanOfJava** [comment]
I have the same problem

**Comment by gabe-scorebreak** [comment]
I have the same issue

**Comment by A-janjan** [comment]
I have the same problem
