### ISSUE TITLE
Encountered a "IndexError: list index out of range" error when using torch2trt(model,[x])

### ISSUE THREAD

**Issue by zang5xixi** [NVIDIA-AI-IOT/torch2trt#670]
I wanted to convert a pytorch model into tensorRT, but encountered such a error:
## error log

```
Traceback (most recent call last):
  File "speaker_verification_cosine1.py", line 269, in <module>
    model_trt = torch2trt(params["embedding_model"], [x,lens])
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.3.0-py3.6-linux-aarch64.egg/torch2trt/torch2trt.py", line 553, in torch2trt
    outputs = module(*inputs)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nvidia/sdcard_zangbin/speechbrain/speechbrain/lobes/models/ECAPA_TDNN.py", line 467, in forward
    x = layer(x)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nvidia/sdcard_zangbin/speechbrain/speechbrain/lobes/models/ECAPA_TDNN.py", line 72, in forward
    return self.norm(self.activation(self.conv(x)))
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nvidia/sdcard_zangbin/speechbrain/speechbrain/nnet/CNN.py", line 395, in forward
    x, self.kernel_size, self.dilation, self.stride
  File "/home/nvidia/sdcard_zangbin/speechbrain/speechbrain/nnet/CNN.py", line 446, in _manage_padding
    x = F.pad(x, padding, mode=self.padding_mode)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.3.0-py3.6-linux-aarch64.egg/torch2trt/torch2trt.py", line 300, in wrapper
    converter["converter"](ctx)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.3.0-py3.6-linux-aarch64.egg/torch2trt/converters/pad.py", line 12, in convert_pad
    pre_padding = (pad[2], pad[0])
IndexError: list index out of range
```

In my pytorch code, i wanted to get a same size tensor after feeding x (shape[8,120,80]) into Conv1d(80,1024,kernel_size=(5,),stride=1), so i needed to add zero-padding into the tensor x.  The question was that the padding computed is 2-d, but convert_pad(ctx) needed a 4-d args. Here are codes relevant:

```
class Conv1d(nn.Module):

    def __init__(
            self,
            out_channels,
            kernel_size,
            input_shape=None,
            in_channels=None,
            stride=1,
            dilation=1,
            padding="same",
            groups=1,
            bias=True,
            padding_mode="reflect",
            skip_transpose=False,
    ):
        super().__init__()
        self.kernel_size = kernel_size
        self.stride = stride
        self.dilation = dilation
        self.padding = padding
        self.padding_mode = padding_mode
        self.unsqueeze = False
        self.skip_transpose = skip_transpose

        if input_shape is None and in_channels is None:
            raise ValueError("Must provide one of input_shape or in_channels")

        if in_channels is None:
            in_channels = self._check_input_shape(input_shape)

        self.conv = nn.Conv1d(
            in_channels,
            out_channels,
            self.kernel_size,
            stride=self.stride,
            dilation=self.dilation,
            padding=0,
            groups=groups,
            bias=bias,
        )

    def forward(self, x):
        if not self.skip_transpose:
            x = x.transpose(1, -1)

        if self.unsqueeze:
            x = x.unsqueeze(1)

        if self.padding == "same":    # To get  same size output
            x = self._manage_padding(
                x, self.kernel_size, self.dilation, self.stride
            )
        elif self.padding == "causal":
            num_pad = (self.kernel_size - 1) * self.dilation
            x = F.pad(x, (num_pad, 0))

        elif self.padding == "valid":
            pass

        else:
            raise ValueError(
                "Padding must be 'same', 'valid' or 'causal'. Got "
                + self.padding
            )

        wx = self.conv(x)

        if self.unsqueeze:
            wx = wx.squeeze(1)

        if not self.skip_transpose:
            wx = wx.transpose(1, -1)

        return wx
```
```
    def _manage_padding(
            self, x, kernel_size: int, dilation: int, stride: int,
    ):
        """This function performs zero-padding on the time axis
        such that their lengths is unchanged after the convolution.

        Arguments
        ---------
        x : torch.Tensor
            Input tensor.
        kernel_size : int
            Size of kernel.
        dilation : int
            Dilation used.
        stride : int
            Stride.
        """

        # Detecting input shape
        L_in = x.shape[-1]
        print('L_in',L_in)

        # Time padding
        padding = get_padding_elem(L_in, stride, kernel_size, dilation)

        # Applying padding
        x = F.pad(x, padding, mode=self.padding_mode)

        return x
```
```
def get_padding_elem(L_in: int, stride: int, kernel_size: int, dilation: int):
    """This function computes the number of elements to add for zero-padding.

    Arguments
    ---------
    L_in : int
    stride: int
    kernel_size : int
    dilation : int
    """
    if stride > 1:
        n_steps = math.ceil(((L_in - kernel_size * dilation) / stride) + 1)
        L_out = stride * (n_steps - 1) + kernel_size * dilation
        padding = [kernel_size // 2, kernel_size // 2]

    else:
        L_out = (L_in - dilation * (kernel_size - 1) - 1) // stride + 1

        padding = [(L_in - L_out) // 2, (L_in - L_out) // 2]
    return padding
```

```
@tensorrt_converter('torch.nn.functional.pad')
def convert_pad(ctx):
    input = ctx.method_args[0]
    input_trt = add_missing_trt_tensors(ctx.network, [input])[0]
    output = ctx.method_return
    
    pad = ctx.method_args[1]
    pre_padding = (pad[2], pad[0])
    post_padding = (pad[3], pad[1])

    
    # mode / value are ignored since not supported by TensorRT
    
    layer = ctx.network.add_padding(input_trt, pre_padding, post_padding)
    output._trt = layer.get_output(0)
```

**Comment by ducnt18121997** [comment]
hi @zang5xixi, did you solved this?
