### ISSUE TITLE
AttributeError: 'builtin_function_or_method' object has no attribute 'clone'

### ISSUE THREAD

**Issue by aktaseren** [NVIDIA-AI-IOT/torch2trt#675]
Hi, thanks a lot for making this great repo available. 

As instructed in your README.md, I set up my environment and then I just wanted to do the example there below.  However, following calling torch2trt, I got an error : `AttributeError: 'builtin_function_or_method' object has no attribute 'clone'`

`aktaseren@aktaseren-UX310UQK:~/RAPiD/torch2trt$ python 
Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from torch2trt import torch2trt
>>> from torchvision.models.alexnet import alexnet
>>> model = alexnet(pretrained=True).eval().cuda()
Downloading: "https://download.pytorch.org/models/alexnet-owt-4df8aa71.pth" to /home/aktaseren/.cache/torch/checkpoints/alexnet-owt-4df8aa71.pth
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 244418560/244418560 [00:29<00:00, 8225114.89it/s]
>>> x = torch.ones((1,3,224,224)).cuda
>>> model_trt = torch2trt(model, [x])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aktaseren/RAPiD/torch2trt/torch2trt/torch2trt.py", line 516, in torch2trt
    inputs = [tensor.clone()[0:1] for tensor in inputs]  # only run single entry
  File "/home/aktaseren/RAPiD/torch2trt/torch2trt/torch2trt.py", line 516, in <listcomp>
    inputs = [tensor.clone()[0:1] for tensor in inputs]  # only run single entry
AttributeError: 'builtin_function_or_method' object has no attribute 'clone'`

I would be grateful if you can guide me to solve this issue.

**Comment by LiangQ5** [comment]
is solved?
