### ISSUE TITLE
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number (base) [root@A09-R34-I192-88-FZ6JTP2 fastspeech]# git branch

### ISSUE THREAD

**Issue by weixsong** [NVIDIA-AI-IOT/torch2trt#677]
Hi,

In my model, I used a dynamic mask from input length:
```
def get_mask_from_lengths(lengths, max_len=None):
    batch_size = lengths.shape[0]
    if max_len is None:
        max_len = torch.max(lengths)

    ids = torch.arange(0, max_len).unsqueeze(0).expand(batch_size, -1).to(device)
    mask = ids >= lengths.unsqueeze(1).expand(-1, max_len)

    return mask
```

but when I tried to export tensorrt model by torch2trt, I meet the following error:
```
Traceback (most recent call last):
  File "torch2trt_tutorial.py", line 207, in <module>
    model_trt = torch2trt(model, [speakers, texts, src_lens, duration_control])
  File "/export/anaconda3/lib/python3.7/site-packages/torch2trt-0.3.0-py3.7.egg/torch2trt/torch2trt.py", line 553, in torch2trt
    outputs = module(*inputs)
  File "/export/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/export/users/songwei/workspace/FastSpeech/exp02_test/fastspeech/model/fastspeech2.py", line 35, in forward
    src_masks = get_mask_from_lengths(src_lens, max_src_len)
  File "/export/users/songwei/workspace/FastSpeech/exp02_test/fastspeech/utils/tools.py", line 63, in get_mask_from_lengths
    max_len = torch.max(lengths).item()
  File "/export/anaconda3/lib/python3.7/site-packages/torch2trt-0.3.0-py3.7.egg/torch2trt/torch2trt.py", line 300, in wrapper
    converter["converter"](ctx)
  File "/export/anaconda3/lib/python3.7/site-packages/torch2trt-0.3.0-py3.7.egg/torch2trt/converters/max.py", line 33, in convert_max
    __convert_max_reduce(ctx)
  File "/export/anaconda3/lib/python3.7/site-packages/torch2trt-0.3.0-py3.7.egg/torch2trt/converters/max.py", line 21, in __convert_max_reduce
    output_val = ctx.method_return[0]
  File "/export/anaconda3/lib/python3.7/site-packages/torch2trt-0.3.0-py3.7.egg/torch2trt/torch2trt.py", line 291, in wrapper
    outputs = method(*args, **kwargs)
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

```

Even if the item() removed in torch.max(lengths).item(), the error still occurs.

**Comment by weixsong** [comment]
The model is correct because the ORT could load the model and do inference as expected.

We want to convert the ONNX model to TensorRT, it seems the error comes from the mask code:

def get_mask_from_lengths(lengths, max_len=None):
    batch_size = lengths.shape[0]
    if max_len is None:
        max_len = torch.max(lengths)

    ids = torch.arange(0, max_len).unsqueeze(0).expand(batch_size, -1).to(device)
    mask = ids >= lengths.unsqueeze(1).expand(-1, max_len)

    return mask
We also tried using torch2trt to export the TRT model directly, but encountered the below error:

Traceback (most recent call last):
  File "torch2trt_tutorial.py", line 207, in <module>
    model_trt = torch2trt(model, [speakers, texts, src_lens, duration_control])
  File "/export/anaconda3/lib/python3.7/site-packages/torch2trt-0.3.0-py3.7.egg/torch2trt/torch2trt.py", line 553, in torch2trt
    outputs = module(*inputs)
  File "/export/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/export/users/songwei/workspace/FastSpeech/exp02_test/fastspeech/model/fastspeech2.py", line 35, in forward
    src_masks = get_mask_from_lengths(src_lens, max_src_len)
  File "/export/users/songwei/workspace/FastSpeech/exp02_test/fastspeech/utils/tools.py", line 64, in get_mask_from_lengths
    max_len = torch.max(lengths)
  File "/export/anaconda3/lib/python3.7/site-packages/torch2trt-0.3.0-py3.7.egg/torch2trt/torch2trt.py", line 300, in wrapper
    converter["converter"](ctx)
  File "/export/anaconda3/lib/python3.7/site-packages/torch2trt-0.3.0-py3.7.egg/torch2trt/converters/max.py", line 33, in convert_max
    __convert_max_reduce(ctx)
  File "/export/anaconda3/lib/python3.7/site-packages/torch2trt-0.3.0-py3.7.egg/torch2trt/converters/max.py", line 21, in __convert_max_reduce
    output_val = ctx.method_return[0]
  File "/export/anaconda3/lib/python3.7/site-packages/torch2trt-0.3.0-py3.7.egg/torch2trt/torch2trt.py", line 291, in wrapper
    outputs = method(*args, **kwargs)
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

This error is also from the mask code, it seems the ONNX to TRT error and the torch2trt error are from the same part.

This dynamically generated mask is a must for our model because of the dynamic predicted decoder length.
How could we solve this issue?

It seems TRT does not support the torch.arange function?

**Comment by weixsong** [comment]
The model is correct because the ORT could load the model and do inference as expected.

We want to convert the ONNX model to TensorRT, it seems the error comes from the mask code:
```
def get_mask_from_lengths(lengths, max_len=None):
    batch_size = lengths.shape[0]
    if max_len is None:
        max_len = torch.max(lengths)

    ids = torch.arange(0, max_len).unsqueeze(0).expand(batch_size, -1).to(device)
    mask = ids >= lengths.unsqueeze(1).expand(-1, max_len)

    return mask
```

We also tried using torch2trt to export the TRT model directly, but encountered the below error:
```
Traceback (most recent call last):
  File "torch2trt_tutorial.py", line 207, in <module>
    model_trt = torch2trt(model, [speakers, texts, src_lens, duration_control])
  File "/export/anaconda3/lib/python3.7/site-packages/torch2trt-0.3.0-py3.7.egg/torch2trt/torch2trt.py", line 553, in torch2trt
    outputs = module(*inputs)
  File "/export/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/export/users/songwei/workspace/FastSpeech/exp02_test/fastspeech/model/fastspeech2.py", line 35, in forward
    src_masks = get_mask_from_lengths(src_lens, max_src_len)
  File "/export/users/songwei/workspace/FastSpeech/exp02_test/fastspeech/utils/tools.py", line 64, in get_mask_from_lengths
    max_len = torch.max(lengths)
  File "/export/anaconda3/lib/python3.7/site-packages/torch2trt-0.3.0-py3.7.egg/torch2trt/torch2trt.py", line 300, in wrapper
    converter["converter"](ctx)
  File "/export/anaconda3/lib/python3.7/site-packages/torch2trt-0.3.0-py3.7.egg/torch2trt/converters/max.py", line 33, in convert_max
    __convert_max_reduce(ctx)
  File "/export/anaconda3/lib/python3.7/site-packages/torch2trt-0.3.0-py3.7.egg/torch2trt/converters/max.py", line 21, in __convert_max_reduce
    output_val = ctx.method_return[0]
  File "/export/anaconda3/lib/python3.7/site-packages/torch2trt-0.3.0-py3.7.egg/torch2trt/torch2trt.py", line 291, in wrapper
    outputs = method(*args, **kwargs)
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

```

This error is also from the mask code, it seems the ONNX to TRT error and the torch2trt error are from the same part.

This dynamically generated mask is a must for our model because of the dynamic predicted decoder length.
How could we solve this issue?

It seems TRT does not support the torch.arange function?

**Comment by laisimiao** [comment]
Hi, @weixsong have you solved this problem?
I found it may not the problem of `torch.arange` but `torch.max()`. See this tiny example:
```
import torch
import torch.nn as nn
from torch2trt import torch2trt

class Mymodel(nn.Module):
    def __init__(self) -> None:
        super().__init__()

    def forward(self, x:torch.Tensor) -> torch.Tensor:
        x = x.max()
        return x


mymodel = Mymodel().eval().cuda()
print(mymodel)
x = torch.ones((1, 3, 5, 5)).cuda()
model_trt = torch2trt(mymodel, [x])
print("finish")
```
When I run aboved script, I also encounter same error:
```
File "try.py", line 40, in forward
    x = x.max()
  File "/opt/conda/lib/python3.8/site-packages/torch2trt-0.3.0-py3.8.egg/torch2trt/torch2trt.py", line 300, in wrapper
    converter["converter"](ctx)
  File "/opt/conda/lib/python3.8/site-packages/torch2trt-0.3.0-py3.8.egg/torch2trt/converters/max.py", line 33, in convert_max
    __convert_max_reduce(ctx)
  File "/opt/conda/lib/python3.8/site-packages/torch2trt-0.3.0-py3.8.egg/torch2trt/converters/max.py", line 21, in __convert_max_reduce
    output_val = ctx.method_return[0]
  File "/opt/conda/lib/python3.8/site-packages/torch2trt-0.3.0-py3.8.egg/torch2trt/torch2trt.py", line 291, in wrapper
    outputs = method(*args, **kwargs)
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number
```
It's so strange, 'max' is a supported converter and it seems there is bug in trt implement.
Any developer?

**Comment by chaoz-dev** [comment]
Oh wow this issue has been open for a while. I'm running into this error now, I'll have a patch up for this soonish.
