### ISSUE TITLE
Missing required packages in setup.py

### ISSUE THREAD

**Issue by wico-silva** [NVIDIA-AI-IOT/torch2trt#690]
Following the installation instructions and running the command:
`python setup.py install`
will error out with:
```
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

To run `test.sh` there's also other packages that are missing.
I've looked through the code and compiled the following list of packages that are required but not installed or documented:
packaging
- numpy
- PyTorch
- torchvision
- termcolor

**Comment by Skyrelixa** [comment]
> Following the installation instructions and running the command: `python setup.py install` will error out with:
> 
> ```
> Traceback (most recent call last):
>   File "setup.py", line 6, in <module>
>     from packaging import version
> ModuleNotFoundError: No module named 'packaging'
> ```
> 
> To run `test.sh` there's also other packages that are missing. I've looked through the code and compiled the following list of packages that are required but not installed or documented:
> 
>     * packaging
> 
>     * numpy
> 
>     * PyTorch
> 
>     * torchvision
> 
>     * termcolor

I'm not sure about termcolor yet, but you can acquire "packaging" by running the following:
`pip3 install packaging`
