### ISSUE TITLE
OSError: [WinError 127]  Error loading cublas64_11.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by ehdrndd** [NVIDIA-AI-IOT/torch2trt#698]
Hi. i installed TensorRT. i try to do install torch2trt in this repo's README.md...

I type install command
```python setup.py install --plugins```

but, i got error like

```
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import torch
  File "C:\Users\ehdrn\anaconda3\envs\od\lib\site-packages\torch\__init__.py", line 124, in <module>
    raise err
OSError: [WinError 127] 지정된 프로시저를 찾을 수 없습니다. Error loading "C:\Users\ehdrn\anaconda3\envs\od\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.```

but i had cublas64_11.dll in my virtual env's torch/lib...

**Comment by keishatsai** [comment]
I think you that have incompatible version of CUDA.

**Comment by lilili666-hit** [comment]
I have the same problem, have you solved it?

**Comment by YoungJerry** [comment]
Maybe your torch version is higher than the actual version of cuda. I solved this same problem by reinstall a lower version pytorch.

**Comment by lilili666-hit** [comment]
> Maybe your torch version is higher than the actual version of cuda. I solved this same problem by reinstall a lower version pytorch.
i think  my cuda version is too high，and then reinstall it is ok

**Comment by lacorreia65** [comment]
I'm also getting a similar error "Could not load symbol cublasGetSmCountTarget from cublas64_11.dll. Error code 127"

I am not sure how critical is it though.

Using Windows 10, Python 3.10.9, CUDAToolkit 11.3, torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1

**Comment by zzztoben** [comment]
same error，you can see tensorrt.__init__ file，code looks for these dll files in the environment variable，whichever path is found first is used，You can remove the relevant files under the torch.lib folder，Let it find the dll file under the default cuda paht，Generally, the dll file path under cuda is in  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin

**Comment by magicse** [comment]
> I'm also getting a similar error "Could not load symbol cublasGetSmCountTarget from cublas64_11.dll. Error code 127"
> 
> I am not sure how critical is it though.
> 
> Using Windows 10, Python 3.10.9, CUDAToolkit 11.3, torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1

This is because torch 1.12.1+cu113 compiled with wrong library for cu113. CUdNN in package torch==1.12.1+cu113 has version 8.3.2. But CUDA 11.3 dint has CUdNN version 8.3.2. CUdNN 8.3.2 only for CUDA 11.5 and CUDA 10.2 -  https://developer.nvidia.com/rdp/cudnn-archive.
For CUDA 11.3 CUdNN must be 8.2.0, 8.2.1

**Comment by sdwulxr** [comment]
> > I'm also getting a similar error "Could not load symbol cublasGetSmCountTarget from cublas64_11.dll. Error code 127"
> > I am not sure how critical is it though.
> > Using Windows 10, Python 3.10.9, CUDAToolkit 11.3, torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1
> 
> This is because torch 1.12.1+cu113 compiled with wrong library. cuDNN in package torch==1.12.1+cu113 has version 8.3.2. But CUDA 11.3 didn't has cuDNN version 8.3.2. cuDNN 8.3.2 only for CUDA 11.5 and CUDA 10.2 - https://developer.nvidia.com/rdp/cudnn-archive. For CUDA 11.3 cuDNN must be 8.2.0 or 8.2.1
> 
> cuda	cudnn
> 11.5	8.3.3、8.3.2、8.3.1、8.3.0、8.2.1、8.2.0
> 11.4	8.2.4、8.2.2、8.2.1、8.2.0
> 11.3	8.2.1、8.2.0
> 11.2	8.2.1、8.2.0、8.1.1、8.1.0
> 11.1	8.2.1、8.2.0、8.1.1、8.1.0、8.0.5、8.0.5、8.0.4
> 11.0	8.2.1、8.2.0、8.1.1、8.1.0、8.0.5、8.0.4、8.0.3、8.0.2、8.0.1
> 10.2	8.3.3、8.3.2、8.3.1、8.3.0、8.2.4、8.2.2、8.2.1、8.2.0、8.1.1、8.1.0、8.0.5、8.0.4、8.0.3、8.0.2、8.0.1、7.6.5
> 10.1	8.0.5、8.0.4、8.0.3、8.0.2、7.6.5、7.6.4、7.6.3、7.6.2、7.6.1、7.6.0、7.5.1、7.5.0
> 10.0	7.6.5、7.6.4、7.6.3、7.6.2、7.6.1、7.6.0、7.5.1、7.5.0、7.4.2、7.4.1、7.3.1、7.3.0
> 9.2	7.6.5、7.6.4、7.6.3、7.6.2、7.6.1、7.6.0、7.5.1、7.5.0、7.4.2、7.4.1、7.3.1、7.2.1、7.1.4、7.1.2
> 9.1	7.1.3、7.1.2、7.0.5
> 9.0	7.6.5、7.6.4、7.6.3、7.6.2、7.6.1、7.6.0、7.5.1、7.5.0、7.4.2、7.4.1、7.3.1、7.3.0、7.1.4、7.1.3、7.1.2、7.0.5、7.0.4
> 8.0	7.1.4、7.1.3、7.0.5、6.0、5.1、5
> 7.5	5.1、5
> 7.0	4、3
> 6.5	2、1
> cuda	CUDAToolkit	pytorch
> 11.3	11.3	1.10.1、1.10.0、1.9.1、1.9.0、1.8.1
> 11.1	11.1	1.10.0、1.9.1、1.9.0、1.8.1、1.8.0
> 11.0	11.0	1.7.1、1.7.0
> 10.2	10.2	1.10.1、1.10.0、1.9.1、1.9.0、1.8.1、1.8.0、1.7.1、1.7.0、1.6.0、1.5.1、1.5.0
> 10.1	10.1	1.7.1、1.7.0、1.6.0、1.5.1、1.5.0、1.4.0
> 10.0	10.0	1.2.0、1.1.0、1.0.1、1.0.0
> 9.2	9.2	1.7.1、1.7.0、1.6.0、1.5.1、1.5.0、1.4.0、1.2.0
> 9.0	9.0	1.1.0、1.0.1、1.0.0
> 8.0	8.0	1.0.0

Can this situation be resolved? Thanks
