### ISSUE TITLE
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary            Warning: Encountered known unsupported method torch.nn.functional.silu

### ISSUE THREAD

**Issue by yeeyeeing** [NVIDIA-AI-IOT/torch2trt#709]
python3 tools/trt.py -f ./exps/default/yolox_s.py -c ./yolox-s-1189-640x640.pth
2022-03-29 18:56:36.631 | INFO     | __main__:main:57 - loaded checkpoint done.
[03/29/2022-18:56:39] [TRT] [I] [MemUsageChange] Init CUDA: CPU +306, GPU +0, now: CPU 3148, GPU 1827 (MiB)
[03/29/2022-18:56:40] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 3167 MiB, GPU 1827 MiB
[03/29/2022-18:56:40] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 3395 MiB, GPU 1903 MiB
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
/home/heheibhoi/.local/lib/python3.8/site-packages/torch2trt/torch2trt.py:193: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  outputs = method(*args, **kwargs)
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.interpolate
[03/29/2022-18:56:41] [TRT] [E] 4: [graphShapeAnalyzer.cpp::computeOutputExtents::1040] Error Code 4: Miscellaneous ((Unnamed Layer* 93) [Concatenation]: error while computing output extent)
2022-03-29 18:56:41.185 | ERROR    | __main__:<module>:83 - An error has been caught in function '<module>', process 'MainProcess' (11254), thread 'MainThread' (139804774057792):
Traceback (most recent call last):

> File "tools/trt.py", line 83, in <module>
    main()
    └ <function main at 0x7f25480504c0>

  File "/home/heheibhoi/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ ()
           └ <function main at 0x7f255350f1f0>

  File "tools/trt.py", line 62, in main
    model_trt = torch2trt(
                └ <function torch2trt at 0x7f255350d790>

  File "/home/heheibhoi/.local/lib/python3.8/site-packages/torch2trt/torch2trt.py", line 377, in torch2trt
    outputs = module(*inputs)
              │       └ (tensor([[[[1., 1., 1.,  ..., 1., 1., 1.],
              │                   [1., 1., 1.,  ..., 1., 1., 1.],
              │                   [1., 1., 1.,  ..., 1., 1., 1.]...
              └ YOLOX(
                  (backbone): YOLOPAFPN(
                    (backbone): CSPDarknet(
                      (stem): Focus(
                        (conv): BaseConv(
                          (conv): ...
  File "/home/heheibhoi/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {}
           │             └ (tensor([[[[1., 1., 1.,  ..., 1., 1., 1.],
           │                         [1., 1., 1.,  ..., 1., 1., 1.],
           │                         [1., 1., 1.,  ..., 1., 1., 1.]...
           └ <bound method YOLOX.forward of YOLOX(
               (backbone): YOLOPAFPN(
                 (backbone): CSPDarknet(
                   (stem): Focus(
                     (conv...

  File "/home/heheibhoi/YOLOX/yolox/models/yolox.py", line 30, in forward
    fpn_outs = self.backbone(x)
               │             └ tensor([[[[1., 1., 1.,  ..., 1., 1., 1.],
               │                         [1., 1., 1.,  ..., 1., 1., 1.],
               │                         [1., 1., 1.,  ..., 1., 1., 1.],...
               └ YOLOX(
                   (backbone): YOLOPAFPN(
                     (backbone): CSPDarknet(
                       (stem): Focus(
                         (conv): BaseConv(
                           (conv): ...

  File "/home/heheibhoi/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {}
           │             └ (tensor([[[[1., 1., 1.,  ..., 1., 1., 1.],
           │                         [1., 1., 1.,  ..., 1., 1., 1.],
           │                         [1., 1., 1.,  ..., 1., 1., 1.]...
           └ <bound method YOLOPAFPN.forward of YOLOPAFPN(
               (backbone): CSPDarknet(
                 (stem): Focus(
                   (conv): BaseConv(
                     (c...

  File "/home/heheibhoi/YOLOX/yolox/models/yolo_pafpn.py", line 100, in forward
    f_out0 = self.C3_p4(f_out0)  # 1024->512/16
             │          └ tensor([[[[-0.2600, -0.2600, -0.0403,  ..., -0.1133, -0.2264, -0.2264],
             │                      [-0.2600, -0.2600, -0.0403,  ..., -0.1133, ...
             └ YOLOPAFPN(
                 (backbone): CSPDarknet(
                   (stem): Focus(
                     (conv): BaseConv(
                       (conv): Conv2d(12, 32, kernel_size=(3...

  File "/home/heheibhoi/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {}
           │             └ (tensor([[[[-0.2600, -0.2600, -0.0403,  ..., -0.1133, -0.2264, -0.2264],
           │                         [-0.2600, -0.2600, -0.0403,  ..., -0.1133,...
           └ <bound method CSPLayer.forward of CSPLayer(
               (conv1): BaseConv(
                 (conv): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, ...

  File "/home/heheibhoi/YOLOX/yolox/models/network_blocks.py", line 181, in forward
    x_1 = self.conv1(x)
          │          └ tensor([[[[-0.2600, -0.2600, -0.0403,  ..., -0.1133, -0.2264, -0.2264],
          │                      [-0.2600, -0.2600, -0.0403,  ..., -0.1133, ...
          └ CSPLayer(
              (conv1): BaseConv(
                (conv): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
                (bn): BatchNor...

  File "/home/heheibhoi/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {}
           │             └ (tensor([[[[-0.2600, -0.2600, -0.0403,  ..., -0.1133, -0.2264, -0.2264],
           │                         [-0.2600, -0.2600, -0.0403,  ..., -0.1133,...
           └ <bound method BaseConv.forward of BaseConv(
               (conv): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
               (bn):...

  File "/home/heheibhoi/YOLOX/yolox/models/network_blocks.py", line 51, in forward
    return self.act(self.bn(self.conv(x)))
           │        │       │         └ tensor([[[[-0.2600, -0.2600, -0.0403,  ..., -0.1133, -0.2264, -0.2264],
           │        │       │                     [-0.2600, -0.2600, -0.0403,  ..., -0.1133, ...
           │        │       └ BaseConv(
           │        │           (conv): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
           │        │           (bn): BatchNorm2d(128, eps=0.001, momen...
           │        └ BaseConv(
           │            (conv): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
           │            (bn): BatchNorm2d(128, eps=0.001, momen...
           └ BaseConv(
               (conv): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
               (bn): BatchNorm2d(128, eps=0.001, momen...

  File "/home/heheibhoi/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {}
           │             └ (tensor([[[[-0.2600, -0.2600, -0.0403,  ..., -0.1133, -0.2264, -0.2264],
           │                         [-0.2600, -0.2600, -0.0403,  ..., -0.1133,...
           └ <bound method attach_converter.<locals>.wrapper of Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)>
  File "/home/heheibhoi/.local/lib/python3.8/site-packages/torch2trt/torch2trt.py", line 202, in wrapper
    converter['converter'](ctx)
    │                      └ <torch2trt.torch2trt.ConversionContext object at 0x7f2547491940>
    └ {'converter': <function convert_Conv2d at 0x7f2550cdd1f0>, 'is_real': True}
  File "/home/heheibhoi/.local/lib/python3.8/site-packages/torch2trt/converters/Conv2d.py", line 9, in convert_Conv2d
    input_trt = trt_(ctx.network, input)
                │    │   │        └ tensor([[[[-0.2600, -0.2600, -0.0403,  ..., -0.1133, -0.2264, -0.2264],
                │    │   │                    [-0.2600, -0.2600, -0.0403,  ..., -0.1133, ...
                │    │   └ <tensorrt.tensorrt.INetworkDefinition object at 0x7f2546ebb2f0>
                │    └ <torch2trt.torch2trt.ConversionContext object at 0x7f2547491940>
                └ <function trt_ at 0x7f255350d5e0>
  File "/home/heheibhoi/.local/lib/python3.8/site-packages/torch2trt/torch2trt.py", line 116, in trt_
    num_dim = len(t._trt.shape) # non-leaf tensors must already have _trt, get shape from that
                  │ │    └ <property object at 0x7f265ae78720>
                  │ └ <tensorrt.tensorrt.ITensor object at 0x7f2545d79170>
                  └ tensor([[[[-0.2600, -0.2600, -0.0403,  ..., -0.1133, -0.2264, -0.2264],
                              [-0.2600, -0.2600, -0.0403,  ..., -0.1133, ...

ValueError: __len__() should return >= 0

Hello community, i tried to convert pytorch model to TensorRT model, i have set num_classes in in yolox_s.py( ./yolox-s-1189-640x640.pth is a model that recognises only 1 object) as 1 and build torch2trt with plugins, could anyone kindly help me

**Comment by yeeyeeing** [comment]
BTW,my spec is
CUDA-11.6
cudnn 8.3.3
TensorRt 8.4 EA

**Comment by 18871271658** [comment]
same problem, have you ever solve that?
