### ISSUE TITLE
module 'collections' has no attribute 'Sequence'

### ISSUE THREAD

**Issue by black0340** [NVIDIA-AI-IOT/torch2trt#744]
Traceback (most recent call last):
  File "C:\Users\black\Desktop\folder\sungwoo\studyforwork\pytorch\PIDNet-main\models\speed\pidnet_speed.py", line 271, in <module>
    model_trt = torch2trt(model,[input])
  File "C:\Users\black\AppData\Local\Programs\Python\Python310\lib\site-packages\torch2trt-0.3.0-py3.10.egg\torch2trt\torch2trt.py", line 644, in torch2trt
    outputs = module(*inputs)
  File "C:\Users\black\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "C:\Users\black\Desktop\folder\sungwoo\studyforwork\pytorch\PIDNet-main\models\speed\pidnet_speed.py", line 160, in forward
    x_ = self.pag3(x_, self.compression3(x))
  File "C:\Users\black\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "C:\Users\black\Desktop\folder\sungwoo\studyforwork\pytorch\PIDNet-main\models\speed\model_utils_speed.py", line 286, in forward
    y_q = F.interpolate(y_q, size=[input_size[2], input_size[3]],
  File "C:\Users\black\AppData\Local\Programs\Python\Python310\lib\site-packages\torch2trt-0.3.0-py3.10.egg\torch2trt\torch2trt.py", line 300, in wrapper
    converter["converter"](ctx)
  File "C:\Users\black\AppData\Local\Programs\Python\Python310\lib\site-packages\torch2trt-0.3.0-py3.10.egg\torch2trt\converters\interpolate.py", line 69, in convert_interpolate_trt7
    if isinstance(shape, collections.Sequence):
AttributeError: module 'collections' has no attribute 'Sequence'
--------------------------------------------------------------------------------------
I got this error if model has interpolate.
how can i solve this??

my version
window11
python=3.10.4
pytorch=1.13.0
tensorrt=8.4.0.6

**Comment by black0340** [comment]
i changed my python 3.8, pytorch 1.11, tensorrt8.2,
and cuda11.2 
Now its working
I think cuda version was problem
