### ISSUE TITLE
Issue in Converting TPS-ResNet-BiLSTM-Attn pth model to TRT

### ISSUE THREAD

**Issue by kishcs** [NVIDIA-AI-IOT/torch2trt#775]
I am trying to convert `TPS-ResNet-BiLSTM-Attn-case-sensitive.pth` model to `TensorRT`. Model details are given below.

Model: `TPS-ResNet-BiLSTM-Attn-case-sensitive.pth` (downloaded from below git repo)
Git: `https://github.com/clovaai/deep-text-recognition-benchmark`

Input tensor size: `torch.Size([1, 1, 32, 100])`

**Issue (when used `use_onnx=True`)**
```
Traceback (most recent call last):
  File "convert_str_2TRT.py", line 80, in <module>
    model_trt = torch2trt(model, [image], use_onnx=True)
  File "/usr/local/lib/python3.8/dist-packages/torch2trt-0.4.0-py3.8.egg/torch2trt/torch2trt.py", line 710, in torch2trt
    torch.onnx.export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/__init__.py", line 350, in export
    return utils.export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 163, in export
    _export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 727, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 602, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 517, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_trace.py", line 1175, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch2trt-0.4.0-py3.8.egg/torch2trt/flatten_module.py", line 34, in forward
    output = self.module(*args)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/workspace/cv/kishore/experiments/exp_torch2trt/str/model.py", line 79, in forward
    prediction = self.Prediction(contextual_feature.contiguous(), text, is_train, batch_max_length=self.opt.batch_max_length)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/workspace/cv/kishore/experiments/exp_torch2trt/str/modules/prediction.py", line 51, in forward
    char_onehots = self._char_to_onehot(targets, onehot_dim=self.num_classes)
  File "/workspace/cv/kishore/experiments/exp_torch2trt/str/modules/prediction.py", line 17, in _char_to_onehot
    input_char = input_char.unsqueeze(1)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

**Issue (when used `use_onnx=False`)**
```
Warning: Encountered known unsupported method torch.Tensor.is_complex
[TensorRT] ERROR: 2: [symbolicDims.cpp::ndGetC::124] Error Code 2: Internal Error (Assertion d.nbDims >= nbSpatialDims + 1 failed.)
[TensorRT] ERROR: 2: [symbolicDims.cpp::ndGetC::124] Error Code 2: Internal Error (Assertion d.nbDims >= nbSpatialDims + 1 failed.)
[TensorRT] ERROR: 2: [symbolicDims.cpp::ndGetC::124] Error Code 2: Internal Error (Assertion d.nbDims >= nbSpatialDims + 1 failed.)
[TensorRT] ERROR: 2: [symbolicDims.cpp::ndGetC::124] Error Code 2: Internal Error (Assertion d.nbDims >= nbSpatialDims + 1 failed.)
[TensorRT] ERROR: 2: [symbolicDims.cpp::ndGetC::124] Error Code 2: Internal Error (Assertion d.nbDims >= nbSpatialDims + 1 failed.)
[TensorRT] ERROR: 2: [symbolicDims.cpp::ndGetC::124] Error Code 2: Internal Error (Assertion d.nbDims >= nbSpatialDims + 1 failed.)
[TensorRT] ERROR: 3: [network.cpp::addPoolingNd::884] Error Code 3: Internal Error (Parameter check failed at: optimizer/api/network.cpp::addPoolingNd::884, condition: allDimsGtEq(windowSize, 1) && volume(windowSize) < MAX_KERNEL_DIMS_PRODUCT(nbSpatialDims)
)
Traceback (most recent call last):
  File "convert_str_2TRT.py", line 80, in <module>
    model_trt = torch2trt(model, [image], use_onnx=False)
  File "/usr/local/lib/python3.8/dist-packages/torch2trt-0.4.0-py3.8.egg/torch2trt/torch2trt.py", line 736, in torch2trt
    outputs = module(*inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/workspace/cv/kishore/experiments/exp_torch2trt/str/model.py", line 61, in forward
    input = self.Transformation(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/workspace/cv/kishore/experiments/exp_torch2trt/str/modules/transformation.py", line 30, in forward
    batch_C_prime = self.LocalizationNetwork(batch_I)  # batch_size x K x 2
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/workspace/cv/kishore/experiments/exp_torch2trt/str/modules/transformation.py", line 81, in forward
    features = self.conv(batch_I).view(batch_size, -1)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch2trt-0.4.0-py3.8.egg/torch2trt/torch2trt.py", line 307, in wrapper
    converter["converter"](ctx)
  File "/usr/local/lib/python3.8/dist-packages/torch2trt-0.4.0-py3.8.egg/torch2trt/converters/AdaptiveAvgPool2d.py", line 22, in convert_AdaptiveAvgPool2d
    layer.stride = stride
AttributeError: 'NoneType' object has no attribute 'stride'
```

Any help is appreciated.

**Comment by jaybdub** [comment]
Hi @kishcs ,

Thanks for reaching out!

Do you mind sharing the source code that you use to instantiate the PyTorch module and call torch2trt?

Best,
John

**Comment by kishcs** [comment]
@jaybdub 
Hello John,

Thanks for your response.
Here is the code to load the pretrained model.

```
device = torch.device('cuda' if cuda else 'cpu')
model = Model(opt)
model = torch.nn.DataParallel(model).to(device)
model.load_state_dict(torch.load('./TPS-ResNet-BiLSTM-Attn-case-sensitive.pth', map_location=device))
align_collate = AlignCollate(imgH=32, imgW=100, keep_ratio_with_pad=False)
model.eval()
```
The above model loading code is given in the corresponding [github](https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/test.py). This is the same way I load model for inference.

Basically model takes 3 params for inference. For the last two params, I have updated the model.py locally with default values.
`model(image, text_for_pred, is_train=False)`

Then prepare input data and call `torch2trt` as below:
```
x= torch.ones((1, 1, 32, 100)).to(device)
model_trt = torch2trt(model, [x], use_onnx=False)
```

Kindly let me know if any more details are required.

**Comment by WelY1** [comment]
Hello, have you solved the problem? I have also been doing this work recently, and I used  `None-VGG-BiLSTM-CTC` model. So I deleted `text_for_pred` parameter. But another problem occurred, as shown below:
`Warning: Encountered known unsupported method torch.Tensor.__hash__
Warning: Encountered known unsupported method torch.Tensor.__hash__
Warning: Encountered known unsupported method torch.Tensor.__hash__
Warning: Encountered known unsupported method torch.Tensor.get_device
Warning: Encountered known unsupported method torch.Tensor.is_complex
[09/12/2022-18:09:11] [TRT] [E] 3: module.FeatureExtraction.ConvNet.0:1:CONVOLUTION:GPU: at least 4 dimensions are required for input.
[09/12/2022-18:09:11] [TRT] [E] 3: module.FeatureExtraction.ConvNet.0:1:CONVOLUTION:GPU: at least 4 dimensions are required for input.`
I convert model as follow:
`self.net.eval()
 x = torch.ones((1, 3, 32, 100)).cuda()
 model_trt = torch2trt(self.net, [x])`
