### ISSUE TITLE
Can't convert Vision Transformer from timm - TypeError: add_constant(): incompatible function arguments.

### ISSUE THREAD

**Issue by jakubhejhal** [NVIDIA-AI-IOT/torch2trt#882]
The following code:

```python
import torch
from torch2trt import torch2trt
import timm

vit_model = timm.create_model(
    model_name="vit_base_patch16_224_dino",
    pretrained=True,
)

vit_model.to("cuda")
vit_model.eval()

input_shape = (4, 3, 224, 224)
input_data = torch.rand(input_shape, dtype=torch.float32).cuda()
trt_model = torch2trt(vit_model, [input_data])
```

Gives the following error:
```bash
Warning: Encountered known unsupported method torch.Tensor.unbind
Traceback (most recent call last):
  File "/torch2trt_tests/tensorrt_experiments/torch2trt_timm_vis_transformer_pure_timm.py", line 15, in <module>
    trt_model = torch2trt(vit_model, [input_data])
  File "/venv/lib/python3.10/site-packages/torch2trt-0.4.0-py3.10.egg/torch2trt/torch2trt.py", line 779, in torch2trt
    outputs = module(*inputs)
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/timm/models/vision_transformer.py", line 549, in forward
    x = self.forward_features(x)
  File "/venv/lib/python3.10/site-packages/timm/models/vision_transformer.py", line 538, in forward_features
    x = self.blocks(x)
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/timm/models/vision_transformer.py", line 268, in forward
    x = x + self.drop_path1(self.ls1(self.attn(self.norm1(x))))
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/timm/models/vision_transformer.py", line 220, in forward
    attn = (q @ k.transpose(-2, -1)) * self.scale
  File "/venv/lib/python3.10/site-packages/torch2trt-0.4.0-py3.10.egg/torch2trt/torch2trt.py", line 310, in wrapper
    converter["converter"](ctx)
  File "/venv/lib/python3.10/site-packages/torch2trt-0.4.0-py3.10.egg/torch2trt/converters/transpose.py", line 26, in convert_transpose_trt7
    input_trt = add_missing_trt_tensors(ctx.network, [input])[0]
  File "/venv/lib/python3.10/site-packages/torch2trt-0.4.0-py3.10.egg/torch2trt/torch2trt.py", line 176, in add_missing_trt_tensors
    t._trt = network.add_constant(shape, weight).get_output(0)
  File "/venv/lib/python3.10/site-packages/torch2trt-0.4.0-py3.10.egg/torch2trt/torch2trt.py", line 400, in wrapper
    ret = attr(*args, **kwargs)
TypeError: add_constant(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt_bindings.tensorrt.INetworkDefinition, shape: tensorrt_bindings.tensorrt.Dims, weights: tensorrt_bindings.tensorrt.Weights) -> tensorrt_bindings.tensorrt.IConstantLayer

Invoked with: <tensorrt_bindings.tensorrt.INetworkDefinition object at 0x7f01f07f96f0>, (4, 12, 197, 64), array([[[[-1.72472194e-01, -1.28571704e-01, -1.14402324e-01, ...,
          -1.26545317e-02,  5.78989200e-02, -6.65028393e-02],
         [-4.51039612e-01,  4.68602143e-02, -3.21930200e-01, ...,
         ....
         ...,
          -1.62460953e-01, -3.48698556e-01,  1.55591115e-01]]]],
      dtype=float32)
```

I'm using:
```
torch==2.0.1
torch2trt==0.4.0
timm==0.6.13
```

**Comment by usama-baloch** [comment]
@jakubhejhal @shanek16 The `add_constant` layer expects weight argument as `trt.Weights` type but I guess your weight is as torch/numpy array. you need to wrap it into trt.Weights to make it compatible. Try updating the failed line:

`t._trt = network.add_constant(shape, trt.Weights(weight)).get_output(0)`

**Comment by Hukongtao** [comment]
> @jakubhejhal @shanek16 The `add_constant` layer expects weight argument as `trt.Weights` type but I guess your weight is as numpy array. we can't directly feed numpy array to the `add_constant` layer, you need to wrap it into trt.Weights to make it compatible. Try updating the failed line:
> 
> `t._trt = network.add_constant(shape, trt.Weights(weight)).get_output(0)`

I solved the above error according to your suggestion, but encountered new problems during the conversion process
![image](https://github.com/NVIDIA-AI-IOT/torch2trt/assets/16505966/10b8c874-db04-4aca-8ce6-2b3ef4f551a5)

**Comment by usama-baloch** [comment]
> > @jakubhejhal @shanek16 The `add_constant` layer expects weight argument as `trt.Weights` type but I guess your weight is as numpy array. we can't directly feed numpy array to the `add_constant` layer, you need to wrap it into trt.Weights to make it compatible. Try updating the failed line:
> > `t._trt = network.add_constant(shape, trt.Weights(weight)).get_output(0)`
> 
> I solved the above error according to your suggestion, but encountered new problems during the conversion process ![image](https://private-user-images.githubusercontent.com/16505966/345989168-10b8c874-db04-4aca-8ce6-2b3ef4f551a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTU0ODUsIm5iZiI6MTcyMDE1NTE4NSwicGF0aCI6Ii8xNjUwNTk2Ni8zNDU5ODkxNjgtMTBiOGM4NzQtZGIwNC00YWNhLThjZTYtMmIzZWY0ZjU1MWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA0NTMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlOTFiZDk1ZGUwYzUwMDgyNGNjNzg3MTYzMmNmZjQ4ZmQ0YWNlYzc0ZjllMjljMTJhMjQ5MzM0NzMxYzY1NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IoUp_pfyAY1mf6N1KlBPfQxNHnczFFp9Gjlm0HzNCyI)

The Last Error occurs in the slice layer of the network, debug your code and check the inputs and outputs of the slice layers you are using during conversion. 

for more info about how slice layers work, look into this: [Slice Layer](https://docs.nvidia.com/deeplearning/tensorrt/operators/docs/Slice.html)
